version: 2
updates:
  - package-ecosystem: gomod
    directory: '/'
     open-pull-requests-limit: 10
    schedule:
      interval: daily
  - package-ecosystem: "gomod"
    directory: "/tools"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
