run:
  timeout: 5m
  skip-files: []
  # skip-dirs:

linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - gofmt
    - whitespace
    # - unparam
    - exportloopref
    - godot
    - gocritic
    - misspell
    # Errcheck is a program for checking for unchecked errors in go programs.
    - errcheck
    # gosimple: Linter for Go source code that specializes in simplifying a code
    - gosimple
