run:
  timeout: 5m
  skip-files: []
  # skip-dirs:

linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - gofmt
    - whitespace
    # - unparam
    - exportloopref
    - godot
    # - gocritic
    - misspell
