builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
    - freebsd
  goarch:
    - amd64
    - arm64
    - '386'
  ignore:
  binary: '{{ .ProjectName }}_v{{ .Version }}'

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: keybase
    args:
      - pgp
      - sign
      - "-b"
      - "-d"
      - "-i"
      - "${artifact}"
      - "-o"
      - "${signature}"
      - "-k"
      - "{{.Env.KEYBASE_KEY_ID}}"


release:
  prerelease: true
