before:
  hooks:
    - make clean

builds:
  - binary: terraform-provider-snowflake_{{ .Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.GitSha={{.Commit}} -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.Version={{.Version}} -X github.com/chanzuckerberg/terraform-provider-snowflake/pkg/version.Dirty={{.Env.DIRTY}}"

archives:
  - files:
    - none*

release:
  prerelease: false

env_files:
  github_token: ~/.config/goreleaser/github_token
