runner:
  golangci:
    cmd: ./bin/golangci-lint run --out-format=line-number --timeout 5m
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    level: warning
  tfproviderlint:
    cmd: ./bin/tfproviderlint ./...
    errorformat:
      - '%f:%l:%c: %m'
    level: warning