// Code generated by object assertions generator (v0.1.0); DO NOT EDIT.

package objectassert

import (
	"fmt"
	"slices"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/helpers"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/collections"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

type OpenflowRuntimeDetailsAssert struct {
	*assert.SnowflakeObjectAssert[sdk.OpenflowRuntimeDetails, sdk.SchemaObjectIdentifier]
}

func OpenflowRuntimeDetails(t *testing.T, id sdk.SchemaObjectIdentifier) *OpenflowRuntimeDetailsAssert {
	t.Helper()
	return &OpenflowRuntimeDetailsAssert{
		assert.NewSnowflakeObjectAssertWithTestClientObjectProvider(sdk.ObjectType("OpenflowRuntimeDetails"), id, func(testClient *helpers.TestClient) assert.ObjectProvider[sdk.OpenflowRuntimeDetails, sdk.SchemaObjectIdentifier] {
			return testClient.OpenflowRuntime.Describe
		}),
	}
}

func OpenflowRuntimeDetailsFromObject(t *testing.T, openflowRuntimeDetails *sdk.OpenflowRuntimeDetails) *OpenflowRuntimeDetailsAssert {
	t.Helper()
	return &OpenflowRuntimeDetailsAssert{
		assert.NewSnowflakeObjectAssertWithObject(sdk.ObjectType("OpenflowRuntimeDetails"), openflowRuntimeDetails.ID(), openflowRuntimeDetails),
	}
}

func (o *OpenflowRuntimeDetailsAssert) HasId(expected sdk.SchemaObjectIdentifier) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Id.FullyQualifiedName() != expected.FullyQualifiedName() {
			return fmt.Errorf("expected id: %v; got: %v", expected.FullyQualifiedName(), o.Id.FullyQualifiedName())
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasName(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Name != expected {
			return fmt.Errorf("expected name: %v; got: %v", expected, o.Name)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNameNotEmpty() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Name == "" {
			return fmt.Errorf("expected name to be non-empty")
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasStatus(expected sdk.OpenflowRuntimeStatus) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Status != expected {
			return fmt.Errorf("expected status: %v; got: %v", expected, o.Status)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasDeployment(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Deployment != expected {
			return fmt.Errorf("expected deployment: %v; got: %v", expected, o.Deployment)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasDeploymentNotEmpty() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Deployment == "" {
			return fmt.Errorf("expected deployment to be non-empty")
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasMinNodes(expected int) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.MinNodes != expected {
			return fmt.Errorf("expected min nodes: %v; got: %v", expected, o.MinNodes)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasMaxNodes(expected int) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.MaxNodes != expected {
			return fmt.Errorf("expected max nodes: %v; got: %v", expected, o.MaxNodes)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNodeType(expected sdk.OpenflowRuntimeNodeType) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.NodeType != expected {
			return fmt.Errorf("expected node type: %v; got: %v", expected, o.NodeType)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasDisplayName(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.DisplayName == nil {
			return fmt.Errorf("expected display name to have value; got: nil")
		}
		if *o.DisplayName != expected {
			return fmt.Errorf("expected display name: %v; got: %v", expected, *o.DisplayName)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoDisplayName() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.DisplayName != nil {
			return fmt.Errorf("expected display name to be nil; got: %v", *o.DisplayName)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasExternalAccessIntegrations(expected ...sdk.AccountObjectIdentifier) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		mapped := collections.Map(o.ExternalAccessIntegrations, func(item sdk.AccountObjectIdentifier) any { return item.FullyQualifiedName() })
		mappedExpected := collections.Map(expected, func(item sdk.AccountObjectIdentifier) any { return item.FullyQualifiedName() })
		if !slices.Equal(mapped, mappedExpected) {
			return fmt.Errorf("expected external access integrations: %v; got: %v", expected, o.ExternalAccessIntegrations)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoExternalAccessIntegrations() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if len(o.ExternalAccessIntegrations) > 0 {
			return fmt.Errorf("expected external access integrations to be empty; got: %v", o.ExternalAccessIntegrations)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasInitiallySuspended(expected bool) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.InitiallySuspended != expected {
			return fmt.Errorf("expected initially suspended: %v; got: %v", expected, o.InitiallySuspended)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasExecuteAsRole(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.ExecuteAsRole == nil {
			return fmt.Errorf("expected execute as role to have value; got: nil")
		}
		if *o.ExecuteAsRole != expected {
			return fmt.Errorf("expected execute as role: %v; got: %v", expected, *o.ExecuteAsRole)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoExecuteAsRole() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.ExecuteAsRole != nil {
			return fmt.Errorf("expected execute as role to be nil; got: %v", *o.ExecuteAsRole)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasKey(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Key == nil {
			return fmt.Errorf("expected key to have value; got: nil")
		}
		if *o.Key != expected {
			return fmt.Errorf("expected key: %v; got: %v", expected, *o.Key)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoKey() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Key != nil {
			return fmt.Errorf("expected key to be nil; got: %v", *o.Key)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasOwner(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Owner != expected {
			return fmt.Errorf("expected owner: %v; got: %v", expected, o.Owner)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasOwnerNotEmpty() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Owner == "" {
			return fmt.Errorf("expected owner to be non-empty")
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasComment(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Comment == nil {
			return fmt.Errorf("expected comment to have value; got: nil")
		}
		if *o.Comment != expected {
			return fmt.Errorf("expected comment: %v; got: %v", expected, *o.Comment)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoComment() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.Comment != nil {
			return fmt.Errorf("expected comment to be nil; got: %v", *o.Comment)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasServerUrl(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.ServerUrl == nil {
			return fmt.Errorf("expected server url to have value; got: nil")
		}
		if *o.ServerUrl != expected {
			return fmt.Errorf("expected server url: %v; got: %v", expected, *o.ServerUrl)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoServerUrl() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.ServerUrl != nil {
			return fmt.Errorf("expected server url to be nil; got: %v", *o.ServerUrl)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNodeTypeTier(expected string) *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.NodeTypeTier == nil {
			return fmt.Errorf("expected node type tier to have value; got: nil")
		}
		if *o.NodeTypeTier != expected {
			return fmt.Errorf("expected node type tier: %v; got: %v", expected, *o.NodeTypeTier)
		}
		return nil
	})
	return o
}

func (o *OpenflowRuntimeDetailsAssert) HasNoNodeTypeTier() *OpenflowRuntimeDetailsAssert {
	o.AddAssertion(func(t *testing.T, o *sdk.OpenflowRuntimeDetails) error {
		t.Helper()
		if o.NodeTypeTier != nil {
			return fmt.Errorf("expected node type tier to be nil; got: %v", *o.NodeTypeTier)
		}
		return nil
	})
	return o
}
