// Code generated by sdk-to-schema generator; DO NOT EDIT.

package schemas

import (
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

// ShowApplicationRoleSchema represents output of SHOW query for the single ApplicationRole.
var ShowApplicationRoleSchema = map[string]*schema.Schema{
	"created_on": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"name": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"comment": {
		Type:     schema.TypeString,
		Computed: true,
	},
	"owner_role_type": {
		Type:     schema.TypeString,
		Computed: true,
	},
}

var _ = ShowApplicationRoleSchema

func ApplicationRoleToSchema(applicationRole *sdk.ApplicationRole) map[string]any {
	applicationRoleSchema := make(map[string]any)
	applicationRoleSchema["created_on"] = applicationRole.CreatedOn.String()
	applicationRoleSchema["name"] = applicationRole.Name
	applicationRoleSchema["owner"] = applicationRole.Owner
	applicationRoleSchema["comment"] = applicationRole.Comment
	applicationRoleSchema["owner_role_type"] = applicationRole.OwnerRoleType
	return applicationRoleSchema
}

var _ = ApplicationRoleToSchema
