// Code generated by assertions generator; DO NOT EDIT.

package resourceshowoutputassert

import (
	"fmt"
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk"
)

// to ensure sdk package is used
var _ = sdk.Object{}

type FunctionShowOutputAssert struct {
	*assert.ResourceAssert
}

func FunctionShowOutput(t *testing.T, name string) *FunctionShowOutputAssert {
	t.Helper()

	functionAssert := FunctionShowOutputAssert{
		ResourceAssert: assert.NewResourceAssert(name, "show_output"),
	}
	functionAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &functionAssert
}

func ImportedFunctionShowOutput(t *testing.T, id string) *FunctionShowOutputAssert {
	t.Helper()

	functionAssert := FunctionShowOutputAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "show_output"),
	}
	functionAssert.AddAssertion(assert.ValueSet("show_output.#", "1"))
	return &functionAssert
}

////////////////////////////
// Attribute value checks //
////////////////////////////

func (f *FunctionShowOutputAssert) HasCreatedOn(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("created_on", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasName(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("name", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasSchemaName(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("schema_name", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsBuiltin(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_builtin", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsAggregate(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_aggregate", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsAnsi(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_ansi", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasMinNumArguments(expected int) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValueSet("min_num_arguments", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasMaxNumArguments(expected int) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValueSet("max_num_arguments", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasArgumentsOld(expected []sdk.DataType) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("arguments_old", fmt.Sprintf("%v", expected)))
	return f
}

func (f *FunctionShowOutputAssert) HasArgumentsRaw(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("arguments_raw", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasDescription(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("description", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasCatalogName(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("catalog_name", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsTableFunction(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_table_function", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasValidForClustering(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("valid_for_clustering", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsSecure(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_secure", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasSecrets(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("secrets", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasExternalAccessIntegrations(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("external_access_integrations", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsExternalFunction(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_external_function", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasLanguage(expected string) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("language", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsMemoizable(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_memoizable", expected))
	return f
}

func (f *FunctionShowOutputAssert) HasIsDataMetric(expected bool) *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueSet("is_data_metric", expected))
	return f
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (f *FunctionShowOutputAssert) HasNoCreatedOn() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("created_on"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoName() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("name"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoSchemaName() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("schema_name"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsBuiltin() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_builtin"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsAggregate() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_aggregate"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsAnsi() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_ansi"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoMinNumArguments() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValueNotSet("min_num_arguments"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoMaxNumArguments() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValueNotSet("max_num_arguments"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoArgumentsOld() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("arguments_old"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoArgumentsRaw() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("arguments_raw"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoDescription() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("description"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoCatalogName() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("catalog_name"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsTableFunction() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_table_function"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoValidForClustering() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("valid_for_clustering"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsSecure() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_secure"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoSecrets() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("secrets"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoExternalAccessIntegrations() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("external_access_integrations"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsExternalFunction() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_external_function"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoLanguage() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueNotSet("language"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsMemoizable() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_memoizable"))
	return f
}

func (f *FunctionShowOutputAssert) HasNoIsDataMetric() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValueNotSet("is_data_metric"))
	return f
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (f *FunctionShowOutputAssert) HasCreatedOnEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("created_on", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasNameEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("name", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasSchemaNameEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("schema_name", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasArgumentsRawEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("arguments_raw", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasDescriptionEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("description", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasCatalogNameEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("catalog_name", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasSecretsEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("secrets", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasExternalAccessIntegrationsEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("external_access_integrations", ""))
	return f
}

func (f *FunctionShowOutputAssert) HasLanguageEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValueSet("language", ""))
	return f
}

///////////////////////////////
// Attribute presence checks //
///////////////////////////////

func (f *FunctionShowOutputAssert) HasCreatedOnNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("created_on"))
	return f
}

func (f *FunctionShowOutputAssert) HasNameNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("name"))
	return f
}

func (f *FunctionShowOutputAssert) HasSchemaNameNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("schema_name"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsBuiltinNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_builtin"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsAggregateNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_aggregate"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsAnsiNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_ansi"))
	return f
}

func (f *FunctionShowOutputAssert) HasMinNumArgumentsNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValuePresent("min_num_arguments"))
	return f
}

func (f *FunctionShowOutputAssert) HasMaxNumArgumentsNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputIntValuePresent("max_num_arguments"))
	return f
}

func (f *FunctionShowOutputAssert) HasArgumentsOldNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("arguments_old"))
	return f
}

func (f *FunctionShowOutputAssert) HasArgumentsRawNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("arguments_raw"))
	return f
}

func (f *FunctionShowOutputAssert) HasDescriptionNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("description"))
	return f
}

func (f *FunctionShowOutputAssert) HasCatalogNameNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("catalog_name"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsTableFunctionNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_table_function"))
	return f
}

func (f *FunctionShowOutputAssert) HasValidForClusteringNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("valid_for_clustering"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsSecureNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_secure"))
	return f
}

func (f *FunctionShowOutputAssert) HasSecretsNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("secrets"))
	return f
}

func (f *FunctionShowOutputAssert) HasExternalAccessIntegrationsNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("external_access_integrations"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsExternalFunctionNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_external_function"))
	return f
}

func (f *FunctionShowOutputAssert) HasLanguageNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputValuePresent("language"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsMemoizableNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_memoizable"))
	return f
}

func (f *FunctionShowOutputAssert) HasIsDataMetricNotEmpty() *FunctionShowOutputAssert {
	f.AddAssertion(assert.ResourceShowOutputBoolValuePresent("is_data_metric"))
	return f
}
