name: Documentation
description: Issues or feature requests for the documentation.
title: "[Docs]: "
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for raising a documentation issue!

        This form is meant to alert the maintainers to an issue with any of documentation connected with the provider, especially in:
        - [Guide on creating issues + FAQ + Commonly Known Issues](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CREATING_ISSUES.md) - If you would like to create a GitHub issue, please read our guide first. It contains useful links, FAQ, and commonly known issues with solutions that may already solve your case.
        - [Terraform Registry](https://registry.terraform.io/providers/hashicorp/snowflake/latest) (such as resource and data source documentation, guides and examples).
        - [Project README](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/README.md).
        - [Contribution Guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md).
        - [Migration Guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md).

        Documentation edits are generally a bit less involved, so are often a great entrypoint if you've ever been interested in contributing!
        If you would like to contribute to the project, please let us know and refer to the [contribution guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md) for tips on getting started.

  - id: company-name
    type: input
    attributes:
      label: Company Name
      description: Optional field. Providing this information allows us to communicate faster which may lead to faster issue resolution.

  - id: object_type
    type: dropdown
    attributes:
      label: Object type(s)
      description: Choose for which object type(s) the documentation is incorrect (if any).
      multiple: true
      options:
        - resource:account
        - resource:account_parameter
        - resource:account_password_policy
        - resource:alert
        - resource:api_integration
        - resource:database
        - resource:database_role
        - resource:dynamic_table
        - resource:email_notification_integration
        - resource:execute
        - resource:external_function
        - resource:external_oauth_integration
        - resource:external_table
        - resource:failover_group
        - resource:file_format
        - resource:function
        - resource:grant_account_role
        - resource:grant_database_role
        - resource:grant_ownership
        - resource:grant_privileges_to_account_role
        - resource:grant_privileges_to_database_role
        - resource:grant_privileges_to_share
        - resource:managed_account
        - resource:masking_policy
        - resource:materialized_view
        - resource:network_policy
        - resource:network_policy_attachment
        - resource:notification_integration
        - resource:oauth_integration
        - resource:object_parameter
        - resource:password_policy
        - resource:pipe
        - resource:procedure
        - resource:resource_monitor
        - resource:role
        - resource:row_access_policy
        - resource:saml_integration
        - resource:schema
        - resource:scim_integration
        - resource:sequence
        - resource:session_parameter
        - resource:share
        - resource:shared_database
        - resource:stage
        - resource:storage_integration
        - resource:stream
        - resource:table
        - resource:table_column_masking_policy_application
        - resource:table_constraint
        - resource:tag
        - resource:tag_association
        - resource:tag_masking_policy_association
        - resource:task
        - resource:unsafe_execute
        - resource:user
        - resource:user_password_policy_attachment
        - resource:user_public_keys
        - resource:view
        - resource:warehouse
        - data_source:accounts
        - data_source:alerts
        - data_source:current_account
        - data_source:current_role
        - data_source:database
        - data_source:database_roles
        - data_source:databases
        - data_source:dynamic_tables
        - data_source:external_functions
        - data_source:external_tables
        - data_source:failover_groups
        - data_source:file_formats
        - data_source:functions
        - data_source:grants
        - data_source:masking_policies
        - data_source:materialized_views
        - data_source:parameters
        - data_source:pipes
        - data_source:procedures
        - data_source:resource_monitors
        - data_source:roles
        - data_source:row_access_policies
        - data_source:schemas
        - data_source:sequences
        - data_source:shares
        - data_source:stages
        - data_source:storage_integrations
        - data_source:streams
        - data_source:system_generate_scim_access_token
        - data_source:system_get_aws_sns_iam_policy
        - data_source:system_get_privatelink_config
        - data_source:system_get_snowflake_platform_info
        - data_source:tables
        - data_source:tasks
        - data_source:users
        - data_source:views
        - data_source:warehouses

  - id: affected-page-link
    type: input
    attributes:
      label: Documentation Link
      description: Please provide a link to the page with invalid documentation.
    validations:
      required: true

  - id: description
    type: textarea
    attributes:
      label: Description
      description: Please leave a brief description of the issue in the documentation.
    validations:
      required: true

  - id: references
    type: textarea
    attributes:
      label: References
      description: |
        Where possible, please supply links to Snowflake SQL documentation, other GitHub issues (open or closed) or pull requests that give additional context.

        [Information about referencing Github Issues](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests)

  - id: will-contribute
    type: checkboxes
    attributes:
      label: Would you like to implement a fix?
      description: If you plan to implement a fix for this, check this box to let the maintainers and community know (you can update this later if you change your mind).
      options:
        - label: Yeah, I'll take it 😎
