name: Feature Request
description: Something is missing or could be improved.
title: "[Feature]: "
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for raising a feature request!

        Before submitting, we ask that you first search existing issues (also the closed ones) to see if someone else may have submitted the same issue.
        This helps to keep all relevant information in one place, including any potential workarounds.

        If you are not running the latest version of either CLI or the Provider, please consider upgrading as the feature could be already implemented.

        If you would like to contribute to the project, please let us know and refer to the [contribution guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md) for tips on getting started.

        Here's a list of useful links that may answer your question:
        - Guide on [creating issues](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CREATING_ISSUES.md) + [FAQ](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/FAQ.md) + [Commonly Known Issues](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/KNOWN_ISSUES.md) - If you would like to create a GitHub issue, please read those in the first order.
        - [Provider Roadmap](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md)

  - id: company-name
    type: input
    attributes:
      label: Company Name
      description: Optional field. Providing this information allows us to communicate faster which may lead to faster issue resolution.

  - id: use-case
    type: textarea
    attributes:
      label: Use Cases or Problem Statement
      description: What use cases or problems are you trying to solve?
      placeholder: Description of use cases or problems.
    validations:
      required: true

  - id: category
    type: dropdown
    attributes:
      label: Category
      description: |
        Choose an appropriate category for the issue:
        - **data_source** - issue connected to one of the existing/new data sources,
        - **data_type** - issue connected with Snowflake data types handling in the provider,
        - **grants** - issue connected in any way with the grants handling,
        - **identifiers** - issue connected in any way with the object identifier,
        - **import** - issue connected in any way with importing objects into terraform state,
        - **migration** - issue connected with moving between the provider versions,
        - **open-tofu** - topics about OpenTofu,
        - **other** - issue not falling into any existing category,
        - **preview** - issue connected with a preview feature,
        - **provider_config** - issue connected with setting up the provider (configuration, connection, authorization, etc.),
        - **resource** - issue connected to one of the existing/new resources,
        - **show_output** - issue connected with the `show_output,` `describe_output,` and `parameters` computed attributes,
        - **snowflake** - issue ending with missing features in Snowflake or improper Snowflake behavior,
        - **stable** - issue connected with a stable feature,
      multiple: true
      options:
        - category:data_source
        - category:data_type
        - category:grants
        - category:identifiers
        - category:import
        - category:migration
        - category:open-tofu
        - category:other
        - category:preview
        - category:provider_config
        - category:resource
        - category:show_output
        - category:snowflake
        - category:stable
    validations:
      required: true

  - id: object_type
    type: dropdown
    attributes:
      label: Object type(s)
      description: Choose object type(s) causing the issue (if any). Note that for some of the features, the label is shortened due to GitHub limitations.
      multiple: true
      options:
        - resource:account
        - resource:account_authentication_policy_attachment
        - resource:account_role
        - resource:account_password_policy_attachment
        - resource:account_parameter
        - resource:account_password_policy
        - resource:alert
        - resource:api_authn_integration_authz_code_grant
        - resource:api_authn_integration_client_credentials
        - resource:api_authn_integration_jwt_bearer
        - resource:api_integration
        - resource:authentication_policy
        - resource:cortex_search_service
        - resource:database
        - resource:database_role
        - resource:dynamic_table
        - resource:email_notification_integration
        - resource:execute
        - resource:external_function
        - resource:external_oauth_integration
        - resource:external_table
        - resource:external_volume
        - resource:failover_group
        - resource:file_format
        - resource:function
        - resource:function_java
        - resource:function_javascript
        - resource:function_python
        - resource:function_scala
        - resource:function_sql
        - resource:grant_account_role
        - resource:grant_application_role
        - resource:grant_database_role
        - resource:grant_ownership
        - resource:grant_privileges_to_account_role
        - resource:grant_privileges_to_database_role
        - resource:grant_privileges_to_share
        - resource:legacy_service_user
        - resource:managed_account
        - resource:masking_policy
        - resource:materialized_view
        - resource:network_policy
        - resource:network_policy_attachment
        - resource:network_rule
        - resource:notification_integration
        - resource:oauth_integration
        - resource:oauth_integration_for_partner_application
        - resource:oauth_integration_for_custom_clients
        - resource:object_parameter
        - resource:password_policy
        - resource:pipe
        - resource:primary_connection
        - resource:procedure
        - resource:procedure_java
        - resource:procedure_javascript
        - resource:procedure_python
        - resource:procedure_scala
        - resource:procedure_sql
        - resource:resource_monitor
        - resource:role
        - resource:row_access_policy
        - resource:saml_integration
        - resource:saml2_integration
        - resource:schema
        - resource:scim_integration
        - resource:secondary_connection
        - resource:secondary_database
        - resource:secret_with_authorization_code_grant
        - resource:secret_with_basic_authentication
        - resource:secret_with_client_credentials
        - resource:secret_with_generic_string
        - resource:sequence
        - resource:session_parameter
        - resource:service_user
        - resource:share
        - resource:shared_database
        - resource:stage
        - resource:storage_integration
        - resource:stream
        - resource:stream_on_directory_table
        - resource:stream_on_external_table
        - resource:stream_on_table
        - resource:stream_on_view
        - resource:streamlit
        - resource:table
        - resource:table_column_masking_policy_application
        - resource:table_constraint
        - resource:tag
        - resource:tag_association
        - resource:tag_masking_policy_association
        - resource:task
        - resource:unsafe_execute
        - resource:user
        - resource:user_authentication_policy_attachment
        - resource:user_password_policy_attachment
        - resource:user_public_keys
        - resource:view
        - resource:warehouse

        - data_source:accounts
        - data_source:account_roles
        - data_source:alerts
        - data_source:connections
        - data_source:cortex_search_services
        - data_source:current_account
        - data_source:current_role
        - data_source:database
        - data_source:database_role
        - data_source:database_roles
        - data_source:databases
        - data_source:dynamic_tables
        - data_source:external_functions
        - data_source:external_tables
        - data_source:failover_groups
        - data_source:file_formats
        - data_source:functions
        - data_source:grants
        - data_source:masking_policies
        - data_source:materialized_views
        - data_source:network_policies
        - data_source:parameters
        - data_source:pipes
        - data_source:procedures
        - data_source:resource_monitors
        - data_source:roles
        - data_source:row_access_policies
        - data_source:schemas
        - data_source:secrets
        - data_source:security_integrations
        - data_source:sequences
        - data_source:shares
        - data_source:stages
        - data_source:storage_integrations
        - data_source:streams
        - data_source:streamlits
        - data_source:system_generate_scim_access_token
        - data_source:system_get_aws_sns_iam_policy
        - data_source:system_get_privatelink_config
        - data_source:system_get_snowflake_platform_info
        - data_source:tables
        - data_source:tags
        - data_source:tasks
        - data_source:users
        - data_source:views
        - data_source:warehouses

  - id: proposal
    type: textarea
    attributes:
      label: Proposal
      description: What solutions would you prefer?
      placeholder: Description of proposed solutions.

  - id: impact
    type: dropdown
    attributes:
      label: How much impact is this issue causing?
      description: |
        Please choose the appropriate impact for the issue keeping in mind that:
        - **High** - completely not able to use the provider or unexpected destruction of data/infrastructure.
        - **Medium** - unable to upgrade provider version or an issue with potential workaround.
        - **Low** - minor provider code or configuration issues.
      options:
        - High
        - Medium
        - Low
      default:
        2 # Low
    validations:
      required: true

  - id: additional-information
    type: textarea
    attributes:
      label: Additional Information
      description: Are there any additional details about new feature that may be relevant?

  - id: will-contribute
    type: checkboxes
    attributes:
      label: Would you like to implement a fix?
      description: If you plan to implement the feature, check this box to let the maintainers and community know (you can update this later if you change your mind).
      options:
        - label: Yeah, I'll take it 😎
