// Code generated by data source model builder generator (v0.1.0); DO NOT EDIT.

package datasourcemodel

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/datasources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type ConnectionsModel struct {
	Connections tfconfig.Variable `json:"connections,omitempty"`
	Like        tfconfig.Variable `json:"like,omitempty"`

	*config.DatasourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func Connections(
	datasourceName string,
) *ConnectionsModel {
	c := &ConnectionsModel{DatasourceModelMeta: config.DatasourceMeta(datasourceName, datasources.Connections)}
	return c
}

func ConnectionsWithDefaultMeta() *ConnectionsModel {
	c := &ConnectionsModel{DatasourceModelMeta: config.DatasourceDefaultMeta(datasources.Connections)}
	return c
}

///////////////////////////////////////////////////////
// set proper json marshalling and handle depends on //
///////////////////////////////////////////////////////

func (c *ConnectionsModel) MarshalJSON() ([]byte, error) {
	type Alias ConnectionsModel
	return json.Marshal(&struct {
		*Alias
		DependsOn                 []string                      `json:"depends_on,omitempty"`
		SingleAttributeWorkaround config.ReplacementPlaceholder `json:"single_attribute_workaround,omitempty"`
	}{
		Alias:                     (*Alias)(c),
		DependsOn:                 c.DependsOn(),
		SingleAttributeWorkaround: config.SnowflakeProviderConfigSingleAttributeWorkaround,
	})
}

func (c *ConnectionsModel) WithDependsOn(values ...string) *ConnectionsModel {
	c.SetDependsOn(values...)
	return c
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

// connections attribute type is not yet supported, so WithConnections can't be generated

func (c *ConnectionsModel) WithLike(like string) *ConnectionsModel {
	c.Like = tfconfig.StringVariable(like)
	return c
}

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (c *ConnectionsModel) WithConnectionsValue(value tfconfig.Variable) *ConnectionsModel {
	c.Connections = value
	return c
}

func (c *ConnectionsModel) WithLikeValue(value tfconfig.Variable) *ConnectionsModel {
	c.Like = value
	return c
}
