// Code generated by data source model builder generator (v0.1.0); DO NOT EDIT.

package datasourcemodel

import (
	"encoding/json"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/config"
	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/datasources"
	tfconfig "github.com/hashicorp/terraform-plugin-testing/config"
)

type OpenflowConnectorDefinitionsModel struct {
	Like                         tfconfig.Variable `json:"like,omitempty"`
	Limit                        tfconfig.Variable `json:"limit,omitempty"`
	OpenflowConnectorDefinitions tfconfig.Variable `json:"openflow_connector_definitions,omitempty"`

	*config.DatasourceModelMeta
}

/////////////////////////////////////////////////
// Basic builders (resource name and required) //
/////////////////////////////////////////////////

func OpenflowConnectorDefinitions(
	datasourceName string,
) *OpenflowConnectorDefinitionsModel {
	o := &OpenflowConnectorDefinitionsModel{DatasourceModelMeta: config.DatasourceMeta(datasourceName, datasources.OpenflowConnectorDefinitions)}
	return o
}

func OpenflowConnectorDefinitionsWithDefaultMeta() *OpenflowConnectorDefinitionsModel {
	o := &OpenflowConnectorDefinitionsModel{DatasourceModelMeta: config.DatasourceDefaultMeta(datasources.OpenflowConnectorDefinitions)}
	return o
}

///////////////////////////////////////////////////////
// set proper json marshalling and handle depends on //
///////////////////////////////////////////////////////

func (o *OpenflowConnectorDefinitionsModel) MarshalJSON() ([]byte, error) {
	type Alias OpenflowConnectorDefinitionsModel
	return json.Marshal(&struct {
		*Alias
		DependsOn                 []string                      `json:"depends_on,omitempty"`
		SingleAttributeWorkaround config.ReplacementPlaceholder `json:"single_attribute_workaround,omitempty"`
	}{
		Alias:                     (*Alias)(o),
		DependsOn:                 o.DependsOn(),
		SingleAttributeWorkaround: config.SnowflakeProviderConfigSingleAttributeWorkaround,
	})
}

func (o *OpenflowConnectorDefinitionsModel) WithDependsOn(values ...string) *OpenflowConnectorDefinitionsModel {
	o.SetDependsOn(values...)
	return o
}

/////////////////////////////////
// below all the proper values //
/////////////////////////////////

func (o *OpenflowConnectorDefinitionsModel) WithLike(like string) *OpenflowConnectorDefinitionsModel {
	o.Like = tfconfig.StringVariable(like)
	return o
}

// limit attribute type is not yet supported, so WithLimit can't be generated

// openflow_connector_definitions attribute type is not yet supported, so WithOpenflowConnectorDefinitions can't be generated

//////////////////////////////////////////
// below it's possible to set any value //
//////////////////////////////////////////

func (o *OpenflowConnectorDefinitionsModel) WithLikeValue(value tfconfig.Variable) *OpenflowConnectorDefinitionsModel {
	o.Like = value
	return o
}

func (o *OpenflowConnectorDefinitionsModel) WithLimitValue(value tfconfig.Variable) *OpenflowConnectorDefinitionsModel {
	o.Limit = value
	return o
}

func (o *OpenflowConnectorDefinitionsModel) WithOpenflowConnectorDefinitionsValue(value tfconfig.Variable) *OpenflowConnectorDefinitionsModel {
	o.OpenflowConnectorDefinitions = value
	return o
}
