// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

var applicationsTestIdAccountObjectIdentifier = randomAccountObjectIdentifier()

const (
	case_Applications_validation_Create_name_ValidIdentifier                                 testCaseName = "validation_Create_name_ValidIdentifier"
	case_Applications_validation_Create_PackageName_ValidIdentifier                          testCaseName = "validation_Create_PackageName_ValidIdentifier"
	case_Applications_validation_Create_opts_Version_ExactlyOneValueSet_NoneSet              testCaseName = "validation_Create_opts_Version_ExactlyOneValueSet_NoneSet"
	case_Applications_validation_Create_opts_Version_ExactlyOneValueSet_MoreThanOneSet       testCaseName = "validation_Create_opts_Version_ExactlyOneValueSet_MoreThanOneSet"
	case_Applications_sql_Create_basic                                                       testCaseName = "sql_Create_basic"
	case_Applications_sql_Create_all                                                         testCaseName = "sql_Create_all"
	case_Applications_validation_Drop_name_ValidIdentifier                                   testCaseName = "validation_Drop_name_ValidIdentifier"
	case_Applications_sql_Drop_basic                                                         testCaseName = "sql_Drop_basic"
	case_Applications_sql_Drop_all                                                           testCaseName = "sql_Drop_all"
	case_Applications_validation_Alter_name_ValidIdentifier                                  testCaseName = "validation_Alter_name_ValidIdentifier"
	case_Applications_validation_Alter_opts_ExactlyOneValueSet_NoneSet                       testCaseName = "validation_Alter_opts_ExactlyOneValueSet_NoneSet"
	case_Applications_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet                testCaseName = "validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Applications_validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_NoneSet        testCaseName = "validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_NoneSet"
	case_Applications_validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_MoreThanOneSet testCaseName = "validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_MoreThanOneSet"
	case_Applications_sql_Alter_Set                                                          testCaseName = "sql_Alter_Set"
	case_Applications_sql_Alter_Unset                                                        testCaseName = "sql_Alter_Unset"
	case_Applications_sql_Alter_Upgrade                                                      testCaseName = "sql_Alter_Upgrade"
	case_Applications_sql_Alter_UpgradeVersion                                               testCaseName = "sql_Alter_UpgradeVersion"
	case_Applications_sql_Alter_UnsetReferences                                              testCaseName = "sql_Alter_UnsetReferences"
	case_Applications_sql_Alter_SetTags                                                      testCaseName = "sql_Alter_SetTags"
	case_Applications_sql_Alter_UnsetTags                                                    testCaseName = "sql_Alter_UnsetTags"
	case_Applications_sql_Show_basic                                                         testCaseName = "sql_Show_basic"
	case_Applications_sql_Show_all                                                           testCaseName = "sql_Show_all"
	case_Applications_sql_Show_Like                                                          testCaseName = "sql_Show_Like"
	case_Applications_sql_Show_StartsWith                                                    testCaseName = "sql_Show_StartsWith"
	case_Applications_sql_Show_Limit                                                         testCaseName = "sql_Show_Limit"
	case_Applications_validation_Describe_name_ValidIdentifier                               testCaseName = "validation_Describe_name_ValidIdentifier"
	case_Applications_sql_Describe_basic                                                     testCaseName = "sql_Describe_basic"
)

type ApplicationsTestsContext struct {
	Create   *sdkTestCtx[*CreateApplicationOptions]
	Drop     *sdkTestCtx[*DropApplicationOptions]
	Alter    *sdkTestCtx[*AlterApplicationOptions]
	Show     *sdkTestCtx[*ShowApplicationOptions]
	Describe *sdkTestCtx[*DescribeApplicationOptions]
}

var applicationsTests = ApplicationsTestsContext{
	Create: newSdkTestCtx[*CreateApplicationOptions](
		"Applications", "Create",
	).
		withDefaultOpts(func() *CreateApplicationOptions {
			return &CreateApplicationOptions{
				name: applicationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateApplicationOptions]{
				Name:        case_Applications_validation_Create_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateApplicationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateApplicationOptions]{
				Name:        case_Applications_validation_Create_PackageName_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateApplicationOptions) {
					opts.PackageName = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateApplicationOptions]{
				Name:        case_Applications_validation_Create_opts_Version_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateApplicationOptions.Version", "VersionDirectory", "VersionAndPatch"),
				DefaultModify: func(opts *CreateApplicationOptions) {
					opts.Version = &ApplicationVersion{}
					opts.Version.VersionDirectory = nil
					opts.Version.VersionAndPatch = nil
				},
			},
			validationCase[*CreateApplicationOptions]{
				Name:        case_Applications_validation_Create_opts_Version_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateApplicationOptions.Version", "VersionDirectory", "VersionAndPatch"),
				DefaultModify: func(opts *CreateApplicationOptions) {
					opts.Version = &ApplicationVersion{}
					opts.Version.VersionDirectory = new("foo")
					opts.Version.VersionAndPatch = &VersionAndPatch{}
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateApplicationOptions]{
				Name:           case_Applications_sql_Create_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateApplicationOptions]{
				Name: case_Applications_sql_Create_all,
			},
		),
	Drop: newSdkTestCtx[*DropApplicationOptions](
		"Applications", "Drop",
	).
		withDefaultOpts(func() *DropApplicationOptions {
			return &DropApplicationOptions{
				name: applicationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropApplicationOptions]{
				Name:        case_Applications_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropApplicationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DropApplicationOptions]{
				Name:           case_Applications_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropApplicationOptions]{
				Name: case_Applications_sql_Drop_all,
			},
		),
	Alter: newSdkTestCtx[*AlterApplicationOptions](
		"Applications", "Alter",
	).
		withDefaultOpts(func() *AlterApplicationOptions {
			return &AlterApplicationOptions{
				name: applicationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterApplicationOptions]{
				Name:        case_Applications_validation_Alter_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterApplicationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterApplicationOptions]{
				Name:        case_Applications_validation_Alter_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterApplicationOptions", "Set", "Unset", "Upgrade", "UpgradeVersion", "UnsetReferences", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApplicationOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.Upgrade = nil
					opts.UpgradeVersion = nil
					opts.UnsetReferences = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterApplicationOptions]{
				Name:        case_Applications_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterApplicationOptions", "Set", "Unset", "Upgrade", "UpgradeVersion", "UnsetReferences", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterApplicationOptions) {
					opts.Set = &ApplicationSet{}
					opts.Unset = &ApplicationUnset{}
				},
			},
			validationCase[*AlterApplicationOptions]{
				Name:        case_Applications_validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterApplicationOptions.UpgradeVersion", "VersionDirectory", "VersionAndPatch"),
				DefaultModify: func(opts *AlterApplicationOptions) {
					opts.UpgradeVersion = &ApplicationVersion{}
					opts.UpgradeVersion.VersionDirectory = nil
					opts.UpgradeVersion.VersionAndPatch = nil
				},
			},
			validationCase[*AlterApplicationOptions]{
				Name:        case_Applications_validation_Alter_opts_UpgradeVersion_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterApplicationOptions.UpgradeVersion", "VersionDirectory", "VersionAndPatch"),
				DefaultModify: func(opts *AlterApplicationOptions) {
					opts.UpgradeVersion = &ApplicationVersion{}
					opts.UpgradeVersion.VersionDirectory = new("foo")
					opts.UpgradeVersion.VersionAndPatch = &VersionAndPatch{}
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_Set,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_Unset,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_Upgrade,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_UpgradeVersion,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_UnsetReferences,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_SetTags,
			},
			sqlCase[*AlterApplicationOptions]{
				Name: case_Applications_sql_Alter_UnsetTags,
			},
		),
	Show: newSdkTestCtx[*ShowApplicationOptions](
		"Applications", "Show",
	).
		withDefaultOpts(func() *ShowApplicationOptions {
			return &ShowApplicationOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowApplicationOptions]{
				Name:           case_Applications_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowApplicationOptions]{
				Name: case_Applications_sql_Show_all,
			},
			sqlCase[*ShowApplicationOptions]{
				Name: case_Applications_sql_Show_Like,
			},
			sqlCase[*ShowApplicationOptions]{
				Name: case_Applications_sql_Show_StartsWith,
			},
			sqlCase[*ShowApplicationOptions]{
				Name: case_Applications_sql_Show_Limit,
			},
		),
	Describe: newSdkTestCtx[*DescribeApplicationOptions](
		"Applications", "Describe",
	).
		withDefaultOpts(func() *DescribeApplicationOptions {
			return &DescribeApplicationOptions{
				name: applicationsTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DescribeApplicationOptions]{
				Name:        case_Applications_validation_Describe_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DescribeApplicationOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DescribeApplicationOptions]{
				Name:           case_Applications_sql_Describe_basic,
				NoModifyNeeded: true,
			},
		),
}

func TestApplications_Create(t *testing.T) {
	applicationsTests.Create.RunValidationCases(t)
	applicationsTests.Create.RunSqlCases(t)
}

func TestApplications_Drop(t *testing.T) {
	applicationsTests.Drop.RunValidationCases(t)
	applicationsTests.Drop.RunSqlCases(t)
}

func TestApplications_Alter(t *testing.T) {
	applicationsTests.Alter.RunValidationCases(t)
	applicationsTests.Alter.RunSqlCases(t)
}

func TestApplications_Show(t *testing.T) {
	applicationsTests.Show.RunValidationCases(t)
	applicationsTests.Show.RunSqlCases(t)
}

func TestApplications_Describe(t *testing.T) {
	applicationsTests.Describe.RunValidationCases(t)
	applicationsTests.Describe.RunSqlCases(t)
}
