// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

func init() {
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[DatabaseKind]{"DatabaseKind", AllDatabaseKinds, ToDatabaseKind})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[CatalogLinkedDatabaseNamespaceMode]{"CatalogLinkedDatabaseNamespaceMode", AllCatalogLinkedDatabaseNamespaceModes, ToCatalogLinkedDatabaseNamespaceMode})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[CatalogLinkedDatabaseAllowedWriteOperations]{"CatalogLinkedDatabaseAllowedWriteOperations", AllCatalogLinkedDatabaseAllowedWriteOperations, ToCatalogLinkedDatabaseAllowedWriteOperations})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[DatabaseCatalogCaseSensitivity]{"DatabaseCatalogCaseSensitivity", AllDatabaseCatalogCaseSensitivities, ToDatabaseCatalogCaseSensitivity})
}

var databasesTestIdAccountObjectIdentifier = randomAccountObjectIdentifier()

const (
	case_Databases_validation_Create_name_ValidIdentifier                               testCaseName = "validation_Create_name_ValidIdentifier"
	case_Databases_validation_Create_opts_ConflictingFields                             testCaseName = "validation_Create_opts_ConflictingFields"
	case_Databases_validation_Create_ExternalVolume_ValidIdentifierIfSet                testCaseName = "validation_Create_ExternalVolume_ValidIdentifierIfSet"
	case_Databases_validation_Create_Catalog_ValidIdentifierIfSet                       testCaseName = "validation_Create_Catalog_ValidIdentifierIfSet"
	case_Databases_sql_Create_basic                                                     testCaseName = "sql_Create_basic"
	case_Databases_sql_Create_all                                                       testCaseName = "sql_Create_all"
	case_Databases_validation_Clone_name_ValidIdentifier                                testCaseName = "validation_Clone_name_ValidIdentifier"
	case_Databases_validation_Clone_opts_ConflictingFields                              testCaseName = "validation_Clone_opts_ConflictingFields"
	case_Databases_sql_Clone_basic                                                      testCaseName = "sql_Clone_basic"
	case_Databases_validation_CreateShared_name_ValidIdentifier                         testCaseName = "validation_CreateShared_name_ValidIdentifier"
	case_Databases_validation_CreateShared_FromShare_ValidIdentifier                    testCaseName = "validation_CreateShared_FromShare_ValidIdentifier"
	case_Databases_validation_CreateShared_opts_ConflictingFields                       testCaseName = "validation_CreateShared_opts_ConflictingFields"
	case_Databases_validation_CreateShared_ExternalVolume_ValidIdentifierIfSet          testCaseName = "validation_CreateShared_ExternalVolume_ValidIdentifierIfSet"
	case_Databases_validation_CreateShared_Catalog_ValidIdentifierIfSet                 testCaseName = "validation_CreateShared_Catalog_ValidIdentifierIfSet"
	case_Databases_sql_CreateShared_basic                                               testCaseName = "sql_CreateShared_basic"
	case_Databases_sql_CreateShared_all                                                 testCaseName = "sql_CreateShared_all"
	case_Databases_validation_CreateSecondary_name_ValidIdentifier                      testCaseName = "validation_CreateSecondary_name_ValidIdentifier"
	case_Databases_validation_CreateSecondary_PrimaryDatabase_ValidIdentifier           testCaseName = "validation_CreateSecondary_PrimaryDatabase_ValidIdentifier"
	case_Databases_validation_CreateSecondary_opts_ConflictingFields                    testCaseName = "validation_CreateSecondary_opts_ConflictingFields"
	case_Databases_validation_CreateSecondary_ExternalVolume_ValidIdentifierIfSet       testCaseName = "validation_CreateSecondary_ExternalVolume_ValidIdentifierIfSet"
	case_Databases_validation_CreateSecondary_Catalog_ValidIdentifierIfSet              testCaseName = "validation_CreateSecondary_Catalog_ValidIdentifierIfSet"
	case_Databases_sql_CreateSecondary_basic                                            testCaseName = "sql_CreateSecondary_basic"
	case_Databases_sql_CreateSecondary_all                                              testCaseName = "sql_CreateSecondary_all"
	case_Databases_validation_CreateFromListing_name_ValidIdentifier                    testCaseName = "validation_CreateFromListing_name_ValidIdentifier"
	case_Databases_sql_CreateFromListing_basic                                          testCaseName = "sql_CreateFromListing_basic"
	case_Databases_sql_CreateFromListing_all                                            testCaseName = "sql_CreateFromListing_all"
	case_Databases_validation_CreateCatalogLinked_name_ValidIdentifier                  testCaseName = "validation_CreateCatalogLinked_name_ValidIdentifier"
	case_Databases_validation_CreateCatalogLinked_ExternalVolume_ValidIdentifierIfSet   testCaseName = "validation_CreateCatalogLinked_ExternalVolume_ValidIdentifierIfSet"
	case_Databases_validation_CreateCatalogLinked_LinkedCatalog_Catalog_ValidIdentifier testCaseName = "validation_CreateCatalogLinked_LinkedCatalog_Catalog_ValidIdentifier"
	case_Databases_sql_CreateCatalogLinked_basic                                        testCaseName = "sql_CreateCatalogLinked_basic"
	case_Databases_sql_CreateCatalogLinked_all                                          testCaseName = "sql_CreateCatalogLinked_all"
	case_Databases_validation_Alter_name_ValidIdentifier                                testCaseName = "validation_Alter_name_ValidIdentifier"
	case_Databases_validation_Alter_opts_ExactlyOneValueSet_NoneSet                     testCaseName = "validation_Alter_opts_ExactlyOneValueSet_NoneSet"
	case_Databases_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet              testCaseName = "validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Databases_validation_Alter_RenameTo_ValidIdentifierIfSet                       testCaseName = "validation_Alter_RenameTo_ValidIdentifierIfSet"
	case_Databases_validation_Alter_SwapWith_ValidIdentifierIfSet                       testCaseName = "validation_Alter_SwapWith_ValidIdentifierIfSet"
	case_Databases_validation_Alter_Set_ExternalVolume_ValidIdentifierIfSet             testCaseName = "validation_Alter_Set_ExternalVolume_ValidIdentifierIfSet"
	case_Databases_validation_Alter_Set_Catalog_ValidIdentifierIfSet                    testCaseName = "validation_Alter_Set_Catalog_ValidIdentifierIfSet"
	case_Databases_validation_Alter_opts_Set_AtLeastOneValueSet                         testCaseName = "validation_Alter_opts_Set_AtLeastOneValueSet"
	case_Databases_validation_Alter_opts_Unset_AtLeastOneValueSet                       testCaseName = "validation_Alter_opts_Unset_AtLeastOneValueSet"
	case_Databases_sql_Alter_RenameTo                                                   testCaseName = "sql_Alter_RenameTo"
	case_Databases_sql_Alter_Set                                                        testCaseName = "sql_Alter_Set"
	case_Databases_sql_Alter_Unset                                                      testCaseName = "sql_Alter_Unset"
	case_Databases_sql_Alter_SwapWith                                                   testCaseName = "sql_Alter_SwapWith"
	case_Databases_sql_Alter_SetTags                                                    testCaseName = "sql_Alter_SetTags"
	case_Databases_sql_Alter_UnsetTags                                                  testCaseName = "sql_Alter_UnsetTags"
	case_Databases_validation_AlterReplication_name_ValidIdentifier                     testCaseName = "validation_AlterReplication_name_ValidIdentifier"
	case_Databases_validation_AlterReplication_opts_ExactlyOneValueSet_NoneSet          testCaseName = "validation_AlterReplication_opts_ExactlyOneValueSet_NoneSet"
	case_Databases_validation_AlterReplication_opts_ExactlyOneValueSet_MoreThanOneSet   testCaseName = "validation_AlterReplication_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Databases_sql_AlterReplication_EnableReplication                               testCaseName = "sql_AlterReplication_EnableReplication"
	case_Databases_sql_AlterReplication_DisableReplication                              testCaseName = "sql_AlterReplication_DisableReplication"
	case_Databases_sql_AlterReplication_Refresh                                         testCaseName = "sql_AlterReplication_Refresh"
	case_Databases_validation_AlterFailover_name_ValidIdentifier                        testCaseName = "validation_AlterFailover_name_ValidIdentifier"
	case_Databases_validation_AlterFailover_opts_ExactlyOneValueSet_NoneSet             testCaseName = "validation_AlterFailover_opts_ExactlyOneValueSet_NoneSet"
	case_Databases_validation_AlterFailover_opts_ExactlyOneValueSet_MoreThanOneSet      testCaseName = "validation_AlterFailover_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Databases_sql_AlterFailover_EnableFailover                                     testCaseName = "sql_AlterFailover_EnableFailover"
	case_Databases_sql_AlterFailover_DisableFailover                                    testCaseName = "sql_AlterFailover_DisableFailover"
	case_Databases_sql_AlterFailover_Primary                                            testCaseName = "sql_AlterFailover_Primary"
	case_Databases_validation_AlterCatalogLinked_name_ValidIdentifier                   testCaseName = "validation_AlterCatalogLinked_name_ValidIdentifier"
	case_Databases_validation_AlterCatalogLinked_opts_ExactlyOneValueSet_NoneSet        testCaseName = "validation_AlterCatalogLinked_opts_ExactlyOneValueSet_NoneSet"
	case_Databases_validation_AlterCatalogLinked_opts_ExactlyOneValueSet_MoreThanOneSet testCaseName = "validation_AlterCatalogLinked_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Databases_validation_AlterCatalogLinked_opts_Set_AtLeastOneValueSet            testCaseName = "validation_AlterCatalogLinked_opts_Set_AtLeastOneValueSet"
	case_Databases_sql_AlterCatalogLinked_AddToAllowedNamespaces                        testCaseName = "sql_AlterCatalogLinked_AddToAllowedNamespaces"
	case_Databases_sql_AlterCatalogLinked_RemoveFromAllowedNamespaces                   testCaseName = "sql_AlterCatalogLinked_RemoveFromAllowedNamespaces"
	case_Databases_sql_AlterCatalogLinked_UnsetAllowedNamespaces                        testCaseName = "sql_AlterCatalogLinked_UnsetAllowedNamespaces"
	case_Databases_sql_AlterCatalogLinked_AddToBlockedNamespaces                        testCaseName = "sql_AlterCatalogLinked_AddToBlockedNamespaces"
	case_Databases_sql_AlterCatalogLinked_RemoveFromBlockedNamespaces                   testCaseName = "sql_AlterCatalogLinked_RemoveFromBlockedNamespaces"
	case_Databases_sql_AlterCatalogLinked_UnsetBlockedNamespaces                        testCaseName = "sql_AlterCatalogLinked_UnsetBlockedNamespaces"
	case_Databases_sql_AlterCatalogLinked_Set                                           testCaseName = "sql_AlterCatalogLinked_Set"
	case_Databases_validation_Drop_name_ValidIdentifier                                 testCaseName = "validation_Drop_name_ValidIdentifier"
	case_Databases_validation_Drop_opts_ConflictingFields                               testCaseName = "validation_Drop_opts_ConflictingFields"
	case_Databases_sql_Drop_basic                                                       testCaseName = "sql_Drop_basic"
	case_Databases_sql_Drop_all                                                         testCaseName = "sql_Drop_all"
	case_Databases_validation_Undrop_name_ValidIdentifier                               testCaseName = "validation_Undrop_name_ValidIdentifier"
	case_Databases_sql_Undrop_basic                                                     testCaseName = "sql_Undrop_basic"
	case_Databases_sql_Show_basic                                                       testCaseName = "sql_Show_basic"
	case_Databases_sql_Show_all                                                         testCaseName = "sql_Show_all"
	case_Databases_sql_Show_Like                                                        testCaseName = "sql_Show_Like"
	case_Databases_sql_Show_StartsWith                                                  testCaseName = "sql_Show_StartsWith"
	case_Databases_sql_Show_Limit                                                       testCaseName = "sql_Show_Limit"
)

type DatabasesTestsContext struct {
	Create              *sdkTestCtx[*CreateDatabaseOptions]
	Clone               *sdkTestCtx[*CloneDatabaseOptions]
	CreateShared        *sdkTestCtx[*CreateSharedDatabaseOptions]
	CreateSecondary     *sdkTestCtx[*CreateSecondaryDatabaseOptions]
	CreateFromListing   *sdkTestCtx[*CreateFromListingDatabaseOptions]
	CreateCatalogLinked *sdkTestCtx[*CreateCatalogLinkedDatabaseOptions]
	Alter               *sdkTestCtx[*AlterDatabaseOptions]
	AlterReplication    *sdkTestCtx[*AlterReplicationDatabaseOptions]
	AlterFailover       *sdkTestCtx[*AlterFailoverDatabaseOptions]
	AlterCatalogLinked  *sdkTestCtx[*AlterCatalogLinkedDatabaseOptions]
	Drop                *sdkTestCtx[*DropDatabaseOptions]
	Undrop              *sdkTestCtx[*UndropDatabaseOptions]
	Show                *sdkTestCtx[*ShowDatabaseOptions]
}

var databasesTests = DatabasesTestsContext{
	Create: newSdkTestCtx[*CreateDatabaseOptions](
		"Databases", "Create",
	).
		withDefaultOpts(func() *CreateDatabaseOptions {
			return &CreateDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateDatabaseOptions]{
				Name:        case_Databases_validation_Create_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateDatabaseOptions]{
				Name:        case_Databases_validation_Create_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateDatabaseOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateDatabaseOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
			validationCase[*CreateDatabaseOptions]{
				Name:        case_Databases_validation_Create_ExternalVolume_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateDatabaseOptions) {
					opts.ExternalVolume = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateDatabaseOptions]{
				Name:        case_Databases_validation_Create_Catalog_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateDatabaseOptions) {
					opts.Catalog = new(emptyAccountObjectIdentifier)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateDatabaseOptions]{
				Name:           case_Databases_sql_Create_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateDatabaseOptions]{
				Name: case_Databases_sql_Create_all,
			},
		),
	Clone: newSdkTestCtx[*CloneDatabaseOptions](
		"Databases", "Clone",
	).
		withDefaultOpts(func() *CloneDatabaseOptions {
			return &CloneDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CloneDatabaseOptions]{
				Name:        case_Databases_validation_Clone_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CloneDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CloneDatabaseOptions]{
				Name:        case_Databases_validation_Clone_opts_ConflictingFields,
				ExpectedErr: errOneOf("CloneDatabaseOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CloneDatabaseOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CloneDatabaseOptions]{
				Name:           case_Databases_sql_Clone_basic,
				NoModifyNeeded: true,
			},
		),
	CreateShared: newSdkTestCtx[*CreateSharedDatabaseOptions](
		"Databases", "CreateShared",
	).
		withDefaultOpts(func() *CreateSharedDatabaseOptions {
			return &CreateSharedDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateSharedDatabaseOptions]{
				Name:        case_Databases_validation_CreateShared_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSharedDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateSharedDatabaseOptions]{
				Name:        case_Databases_validation_CreateShared_FromShare_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSharedDatabaseOptions) {
					opts.FromShare = emptyExternalObjectIdentifier
				},
			},
			validationCase[*CreateSharedDatabaseOptions]{
				Name:        case_Databases_validation_CreateShared_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateSharedDatabaseOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateSharedDatabaseOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
			validationCase[*CreateSharedDatabaseOptions]{
				Name:        case_Databases_validation_CreateShared_ExternalVolume_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSharedDatabaseOptions) {
					opts.ExternalVolume = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateSharedDatabaseOptions]{
				Name:        case_Databases_validation_CreateShared_Catalog_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSharedDatabaseOptions) {
					opts.Catalog = new(emptyAccountObjectIdentifier)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateSharedDatabaseOptions]{
				Name:           case_Databases_sql_CreateShared_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateSharedDatabaseOptions]{
				Name: case_Databases_sql_CreateShared_all,
			},
		),
	CreateSecondary: newSdkTestCtx[*CreateSecondaryDatabaseOptions](
		"Databases", "CreateSecondary",
	).
		withDefaultOpts(func() *CreateSecondaryDatabaseOptions {
			return &CreateSecondaryDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateSecondaryDatabaseOptions]{
				Name:        case_Databases_validation_CreateSecondary_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSecondaryDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateSecondaryDatabaseOptions]{
				Name:        case_Databases_validation_CreateSecondary_PrimaryDatabase_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSecondaryDatabaseOptions) {
					opts.PrimaryDatabase = emptyExternalObjectIdentifier
				},
			},
			validationCase[*CreateSecondaryDatabaseOptions]{
				Name:        case_Databases_validation_CreateSecondary_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateSecondaryDatabaseOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateSecondaryDatabaseOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
			validationCase[*CreateSecondaryDatabaseOptions]{
				Name:        case_Databases_validation_CreateSecondary_ExternalVolume_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSecondaryDatabaseOptions) {
					opts.ExternalVolume = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateSecondaryDatabaseOptions]{
				Name:        case_Databases_validation_CreateSecondary_Catalog_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateSecondaryDatabaseOptions) {
					opts.Catalog = new(emptyAccountObjectIdentifier)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateSecondaryDatabaseOptions]{
				Name:           case_Databases_sql_CreateSecondary_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateSecondaryDatabaseOptions]{
				Name: case_Databases_sql_CreateSecondary_all,
			},
		),
	CreateFromListing: newSdkTestCtx[*CreateFromListingDatabaseOptions](
		"Databases", "CreateFromListing",
	).
		withDefaultOpts(func() *CreateFromListingDatabaseOptions {
			return &CreateFromListingDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateFromListingDatabaseOptions]{
				Name:        case_Databases_validation_CreateFromListing_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateFromListingDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateFromListingDatabaseOptions]{
				Name:           case_Databases_sql_CreateFromListing_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateFromListingDatabaseOptions]{
				Name: case_Databases_sql_CreateFromListing_all,
			},
		),
	CreateCatalogLinked: newSdkTestCtx[*CreateCatalogLinkedDatabaseOptions](
		"Databases", "CreateCatalogLinked",
	).
		withDefaultOpts(func() *CreateCatalogLinkedDatabaseOptions {
			return &CreateCatalogLinkedDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_CreateCatalogLinked_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateCatalogLinkedDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*CreateCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_CreateCatalogLinked_ExternalVolume_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateCatalogLinkedDatabaseOptions) {
					opts.ExternalVolume = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_CreateCatalogLinked_LinkedCatalog_Catalog_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateCatalogLinkedDatabaseOptions) {
					opts.LinkedCatalog.Catalog = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateCatalogLinkedDatabaseOptions]{
				Name:           case_Databases_sql_CreateCatalogLinked_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_CreateCatalogLinked_all,
			},
		),
	Alter: newSdkTestCtx[*AlterDatabaseOptions](
		"Databases", "Alter",
	).
		withDefaultOpts(func() *AlterDatabaseOptions {
			return &AlterDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterDatabaseOptions", "RenameTo", "Set", "Unset", "SwapWith", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.RenameTo = nil
					opts.Set = nil
					opts.Unset = nil
					opts.SwapWith = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterDatabaseOptions", "RenameTo", "Set", "Unset", "SwapWith", "SetTags", "UnsetTags"),
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.RenameTo = new(randomAccountObjectIdentifier())
					opts.Set = &DatabaseSet{}
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_RenameTo_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.RenameTo = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_SwapWith_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.SwapWith = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_Set_ExternalVolume_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.Set = &DatabaseSet{}
					opts.Set.ExternalVolume = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_Set_Catalog_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.Set = &DatabaseSet{}
					opts.Set.Catalog = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterDatabaseOptions.Set", "DataRetentionTimeInDays", "MaxDataExtensionTimeInDays", "ExternalVolume", "Catalog", "ReplaceInvalidCharacters", "DefaultDdlCollation", "DefaultNotebookComputePoolCpu", "DefaultNotebookComputePoolGpu", "StorageSerializationPolicy", "LogLevel", "LogEventLevel", "TraceLevel", "SuspendTaskAfterNumFailures", "TaskAutoRetryAttempts", "UserTaskManagedInitialWarehouseSize", "UserTaskTimeoutMs", "UserTaskMinimumTriggerIntervalInSeconds", "QuotedIdentifiersIgnoreCase", "EnableConsoleOutput", "Comment"),
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.Set = &DatabaseSet{}
					opts.Set.DataRetentionTimeInDays = nil
					opts.Set.MaxDataExtensionTimeInDays = nil
					opts.Set.ExternalVolume = nil
					opts.Set.Catalog = nil
					opts.Set.ReplaceInvalidCharacters = nil
					opts.Set.DefaultDdlCollation = nil
					opts.Set.DefaultNotebookComputePoolCpu = nil
					opts.Set.DefaultNotebookComputePoolGpu = nil
					opts.Set.StorageSerializationPolicy = nil
					opts.Set.LogLevel = nil
					opts.Set.LogEventLevel = nil
					opts.Set.TraceLevel = nil
					opts.Set.SuspendTaskAfterNumFailures = nil
					opts.Set.TaskAutoRetryAttempts = nil
					opts.Set.UserTaskManagedInitialWarehouseSize = nil
					opts.Set.UserTaskTimeoutMs = nil
					opts.Set.UserTaskMinimumTriggerIntervalInSeconds = nil
					opts.Set.QuotedIdentifiersIgnoreCase = nil
					opts.Set.EnableConsoleOutput = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterDatabaseOptions]{
				Name:        case_Databases_validation_Alter_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterDatabaseOptions.Unset", "DataRetentionTimeInDays", "MaxDataExtensionTimeInDays", "ExternalVolume", "Catalog", "ReplaceInvalidCharacters", "DefaultDdlCollation", "DefaultNotebookComputePoolCpu", "DefaultNotebookComputePoolGpu", "StorageSerializationPolicy", "LogLevel", "LogEventLevel", "TraceLevel", "SuspendTaskAfterNumFailures", "TaskAutoRetryAttempts", "UserTaskManagedInitialWarehouseSize", "UserTaskTimeoutMs", "UserTaskMinimumTriggerIntervalInSeconds", "QuotedIdentifiersIgnoreCase", "EnableConsoleOutput", "Comment"),
				DefaultModify: func(opts *AlterDatabaseOptions) {
					opts.Unset = &DatabaseUnset{}
					opts.Unset.DataRetentionTimeInDays = nil
					opts.Unset.MaxDataExtensionTimeInDays = nil
					opts.Unset.ExternalVolume = nil
					opts.Unset.Catalog = nil
					opts.Unset.ReplaceInvalidCharacters = nil
					opts.Unset.DefaultDdlCollation = nil
					opts.Unset.DefaultNotebookComputePoolCpu = nil
					opts.Unset.DefaultNotebookComputePoolGpu = nil
					opts.Unset.StorageSerializationPolicy = nil
					opts.Unset.LogLevel = nil
					opts.Unset.LogEventLevel = nil
					opts.Unset.TraceLevel = nil
					opts.Unset.SuspendTaskAfterNumFailures = nil
					opts.Unset.TaskAutoRetryAttempts = nil
					opts.Unset.UserTaskManagedInitialWarehouseSize = nil
					opts.Unset.UserTaskTimeoutMs = nil
					opts.Unset.UserTaskMinimumTriggerIntervalInSeconds = nil
					opts.Unset.QuotedIdentifiersIgnoreCase = nil
					opts.Unset.EnableConsoleOutput = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_RenameTo,
			},
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_Set,
			},
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_Unset,
			},
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_SwapWith,
			},
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_SetTags,
			},
			sqlCase[*AlterDatabaseOptions]{
				Name: case_Databases_sql_Alter_UnsetTags,
			},
		),
	AlterReplication: newSdkTestCtx[*AlterReplicationDatabaseOptions](
		"Databases", "AlterReplication",
	).
		withDefaultOpts(func() *AlterReplicationDatabaseOptions {
			return &AlterReplicationDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterReplicationDatabaseOptions]{
				Name:        case_Databases_validation_AlterReplication_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterReplicationDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterReplicationDatabaseOptions]{
				Name:        case_Databases_validation_AlterReplication_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterReplicationDatabaseOptions", "EnableReplication", "DisableReplication", "Refresh"),
				DefaultModify: func(opts *AlterReplicationDatabaseOptions) {
					opts.EnableReplication = nil
					opts.DisableReplication = nil
					opts.Refresh = nil
				},
			},
			validationCase[*AlterReplicationDatabaseOptions]{
				Name:        case_Databases_validation_AlterReplication_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterReplicationDatabaseOptions", "EnableReplication", "DisableReplication", "Refresh"),
				DefaultModify: func(opts *AlterReplicationDatabaseOptions) {
					opts.EnableReplication = &EnableReplication{}
					opts.DisableReplication = &DisableReplication{}
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterReplicationDatabaseOptions]{
				Name: case_Databases_sql_AlterReplication_EnableReplication,
			},
			sqlCase[*AlterReplicationDatabaseOptions]{
				Name: case_Databases_sql_AlterReplication_DisableReplication,
			},
			sqlCase[*AlterReplicationDatabaseOptions]{
				Name: case_Databases_sql_AlterReplication_Refresh,
			},
		),
	AlterFailover: newSdkTestCtx[*AlterFailoverDatabaseOptions](
		"Databases", "AlterFailover",
	).
		withDefaultOpts(func() *AlterFailoverDatabaseOptions {
			return &AlterFailoverDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterFailoverDatabaseOptions]{
				Name:        case_Databases_validation_AlterFailover_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterFailoverDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterFailoverDatabaseOptions]{
				Name:        case_Databases_validation_AlterFailover_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterFailoverDatabaseOptions", "EnableFailover", "DisableFailover", "Primary"),
				DefaultModify: func(opts *AlterFailoverDatabaseOptions) {
					opts.EnableFailover = nil
					opts.DisableFailover = nil
					opts.Primary = nil
				},
			},
			validationCase[*AlterFailoverDatabaseOptions]{
				Name:        case_Databases_validation_AlterFailover_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterFailoverDatabaseOptions", "EnableFailover", "DisableFailover", "Primary"),
				DefaultModify: func(opts *AlterFailoverDatabaseOptions) {
					opts.EnableFailover = &EnableFailover{}
					opts.DisableFailover = &DisableFailover{}
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterFailoverDatabaseOptions]{
				Name: case_Databases_sql_AlterFailover_EnableFailover,
			},
			sqlCase[*AlterFailoverDatabaseOptions]{
				Name: case_Databases_sql_AlterFailover_DisableFailover,
			},
			sqlCase[*AlterFailoverDatabaseOptions]{
				Name: case_Databases_sql_AlterFailover_Primary,
			},
		),
	AlterCatalogLinked: newSdkTestCtx[*AlterCatalogLinkedDatabaseOptions](
		"Databases", "AlterCatalogLinked",
	).
		withDefaultOpts(func() *AlterCatalogLinkedDatabaseOptions {
			return &AlterCatalogLinkedDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_AlterCatalogLinked_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterCatalogLinkedDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*AlterCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_AlterCatalogLinked_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCatalogLinkedDatabaseOptions", "AddToAllowedNamespaces", "RemoveFromAllowedNamespaces", "UnsetAllowedNamespaces", "AddToBlockedNamespaces", "RemoveFromBlockedNamespaces", "UnsetBlockedNamespaces", "Set"),
				DefaultModify: func(opts *AlterCatalogLinkedDatabaseOptions) {
					opts.AddToAllowedNamespaces = nil
					opts.RemoveFromAllowedNamespaces = nil
					opts.UnsetAllowedNamespaces = nil
					opts.AddToBlockedNamespaces = nil
					opts.RemoveFromBlockedNamespaces = nil
					opts.UnsetBlockedNamespaces = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_AlterCatalogLinked_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCatalogLinkedDatabaseOptions", "AddToAllowedNamespaces", "RemoveFromAllowedNamespaces", "UnsetAllowedNamespaces", "AddToBlockedNamespaces", "RemoveFromBlockedNamespaces", "UnsetBlockedNamespaces", "Set"),
				DefaultModify: func(opts *AlterCatalogLinkedDatabaseOptions) {
					opts.AddToAllowedNamespaces = &AddToAllowedNamespaces{}
					opts.RemoveFromAllowedNamespaces = &RemoveFromAllowedNamespaces{}
				},
			},
			validationCase[*AlterCatalogLinkedDatabaseOptions]{
				Name:        case_Databases_validation_AlterCatalogLinked_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterCatalogLinkedDatabaseOptions.Set", "SyncIntervalSeconds", "AllowedWriteOperations"),
				DefaultModify: func(opts *AlterCatalogLinkedDatabaseOptions) {
					opts.Set = &CatalogLinkedDatabaseSet{}
					opts.Set.SyncIntervalSeconds = nil
					opts.Set.AllowedWriteOperations = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_AddToAllowedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_RemoveFromAllowedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_UnsetAllowedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_AddToBlockedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_RemoveFromBlockedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_UnsetBlockedNamespaces,
			},
			sqlCase[*AlterCatalogLinkedDatabaseOptions]{
				Name: case_Databases_sql_AlterCatalogLinked_Set,
			},
		),
	Drop: newSdkTestCtx[*DropDatabaseOptions](
		"Databases", "Drop",
	).
		withDefaultOpts(func() *DropDatabaseOptions {
			return &DropDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropDatabaseOptions]{
				Name:        case_Databases_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
			validationCase[*DropDatabaseOptions]{
				Name:        case_Databases_validation_Drop_opts_ConflictingFields,
				ExpectedErr: errOneOf("DropDatabaseOptions", "Cascade", "Restrict"),
				DefaultModify: func(opts *DropDatabaseOptions) {
					opts.Cascade = new(true)
					opts.Restrict = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*DropDatabaseOptions]{
				Name:           case_Databases_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropDatabaseOptions]{
				Name: case_Databases_sql_Drop_all,
			},
		),
	Undrop: newSdkTestCtx[*UndropDatabaseOptions](
		"Databases", "Undrop",
	).
		withDefaultOpts(func() *UndropDatabaseOptions {
			return &UndropDatabaseOptions{
				name: databasesTestIdAccountObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*UndropDatabaseOptions]{
				Name:        case_Databases_validation_Undrop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *UndropDatabaseOptions) {
					opts.name = emptyAccountObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*UndropDatabaseOptions]{
				Name:           case_Databases_sql_Undrop_basic,
				NoModifyNeeded: true,
			},
		),
	Show: newSdkTestCtx[*ShowDatabaseOptions](
		"Databases", "Show",
	).
		withDefaultOpts(func() *ShowDatabaseOptions {
			return &ShowDatabaseOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowDatabaseOptions]{
				Name:           case_Databases_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowDatabaseOptions]{
				Name: case_Databases_sql_Show_all,
			},
			sqlCase[*ShowDatabaseOptions]{
				Name: case_Databases_sql_Show_Like,
			},
			sqlCase[*ShowDatabaseOptions]{
				Name: case_Databases_sql_Show_StartsWith,
			},
			sqlCase[*ShowDatabaseOptions]{
				Name: case_Databases_sql_Show_Limit,
			},
		),
}

func TestDatabases_Create(t *testing.T) {
	databasesTests.Create.RunValidationCases(t)
	databasesTests.Create.RunSqlCases(t)
}

func TestDatabases_Clone(t *testing.T) {
	databasesTests.Clone.RunValidationCases(t)
	databasesTests.Clone.RunSqlCases(t)
}

func TestDatabases_CreateShared(t *testing.T) {
	databasesTests.CreateShared.RunValidationCases(t)
	databasesTests.CreateShared.RunSqlCases(t)
}

func TestDatabases_CreateSecondary(t *testing.T) {
	databasesTests.CreateSecondary.RunValidationCases(t)
	databasesTests.CreateSecondary.RunSqlCases(t)
}

func TestDatabases_CreateFromListing(t *testing.T) {
	databasesTests.CreateFromListing.RunValidationCases(t)
	databasesTests.CreateFromListing.RunSqlCases(t)
}

func TestDatabases_CreateCatalogLinked(t *testing.T) {
	databasesTests.CreateCatalogLinked.RunValidationCases(t)
	databasesTests.CreateCatalogLinked.RunSqlCases(t)
}

func TestDatabases_Alter(t *testing.T) {
	databasesTests.Alter.RunValidationCases(t)
	databasesTests.Alter.RunSqlCases(t)
}

func TestDatabases_AlterReplication(t *testing.T) {
	databasesTests.AlterReplication.RunValidationCases(t)
	databasesTests.AlterReplication.RunSqlCases(t)
}

func TestDatabases_AlterFailover(t *testing.T) {
	databasesTests.AlterFailover.RunValidationCases(t)
	databasesTests.AlterFailover.RunSqlCases(t)
}

func TestDatabases_AlterCatalogLinked(t *testing.T) {
	databasesTests.AlterCatalogLinked.RunValidationCases(t)
	databasesTests.AlterCatalogLinked.RunSqlCases(t)
}

func TestDatabases_Drop(t *testing.T) {
	databasesTests.Drop.RunValidationCases(t)
	databasesTests.Drop.RunSqlCases(t)
}

func TestDatabases_Undrop(t *testing.T) {
	databasesTests.Undrop.RunValidationCases(t)
	databasesTests.Undrop.RunSqlCases(t)
}

func TestDatabases_Show(t *testing.T) {
	databasesTests.Show.RunValidationCases(t)
	databasesTests.Show.RunSqlCases(t)
}
