// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

func init() {
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[FileFormatType]{"FileFormatType", AllFileFormatTypes, ToFileFormatType})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[BinaryFormat]{"BinaryFormat", AllBinaryFormats, ToBinaryFormat})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[CsvCompression]{"CsvCompression", AllCsvCompressions, ToCsvCompression})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[CsvEncoding]{"CsvEncoding", AllCsvEncodings, ToCsvEncoding})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[JsonCompression]{"JsonCompression", AllJsonCompressions, ToJsonCompression})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[AvroCompression]{"AvroCompression", AllAvroCompressions, ToAvroCompression})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[ParquetCompression]{"ParquetCompression", AllParquetCompressions, ToParquetCompression})
	allEnumConversionTests = append(allEnumConversionTests, typedEnumTestProvider[XmlCompression]{"XmlCompression", AllXmlCompressions, ToXmlCompression})
}

var fileFormatsTestIdSchemaObjectIdentifier = randomSchemaObjectIdentifier()

const (
	case_FileFormats_validation_CreateCsv_opts_ConflictingFields_SkipHeader_ParseHeader                       testCaseName = "validation_CreateCsv_opts_ConflictingFields_SkipHeader_ParseHeader"
	case_FileFormats_validation_CreateCsv_name_ValidIdentifier                                                testCaseName = "validation_CreateCsv_name_ValidIdentifier"
	case_FileFormats_validation_CreateCsv_opts_ConflictingFields_OrReplace_IfNotExists                        testCaseName = "validation_CreateCsv_opts_ConflictingFields_OrReplace_IfNotExists"
	case_FileFormats_validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_NoneSet                     testCaseName = "validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet              testCaseName = "validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_NoneSet                      testCaseName = "validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet               testCaseName = "validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_NoneSet                          testCaseName = "validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet                   testCaseName = "validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_NoneSet                          testCaseName = "validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet                   testCaseName = "validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_NoneSet                     testCaseName = "validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet              testCaseName = "validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_Escape_ExactlyOneValueSet_NoneSet                              testCaseName = "validation_CreateCsv_opts_Escape_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_Escape_ExactlyOneValueSet_MoreThanOneSet                       testCaseName = "validation_CreateCsv_opts_Escape_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet               testCaseName = "validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet        testCaseName = "validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet           testCaseName = "validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet    testCaseName = "validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_CreateCsv_basic                                                                      testCaseName = "sql_CreateCsv_basic"
	case_FileFormats_sql_CreateCsv_all                                                                        testCaseName = "sql_CreateCsv_all"
	case_FileFormats_validation_CreateJson_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters   testCaseName = "validation_CreateJson_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters"
	case_FileFormats_validation_CreateJson_name_ValidIdentifier                                               testCaseName = "validation_CreateJson_name_ValidIdentifier"
	case_FileFormats_validation_CreateJson_opts_ConflictingFields_OrReplace_IfNotExists                       testCaseName = "validation_CreateJson_opts_ConflictingFields_OrReplace_IfNotExists"
	case_FileFormats_validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_NoneSet                         testCaseName = "validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet                  testCaseName = "validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_NoneSet                         testCaseName = "validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet                  testCaseName = "validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_NoneSet                    testCaseName = "validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet             testCaseName = "validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_CreateJson_basic                                                                     testCaseName = "sql_CreateJson_basic"
	case_FileFormats_sql_CreateJson_all                                                                       testCaseName = "sql_CreateJson_all"
	case_FileFormats_validation_CreateAvro_name_ValidIdentifier                                               testCaseName = "validation_CreateAvro_name_ValidIdentifier"
	case_FileFormats_validation_CreateAvro_opts_ConflictingFields                                             testCaseName = "validation_CreateAvro_opts_ConflictingFields"
	case_FileFormats_sql_CreateAvro_basic                                                                     testCaseName = "sql_CreateAvro_basic"
	case_FileFormats_sql_CreateAvro_all                                                                       testCaseName = "sql_CreateAvro_all"
	case_FileFormats_validation_CreateOrc_name_ValidIdentifier                                                testCaseName = "validation_CreateOrc_name_ValidIdentifier"
	case_FileFormats_validation_CreateOrc_opts_ConflictingFields                                              testCaseName = "validation_CreateOrc_opts_ConflictingFields"
	case_FileFormats_sql_CreateOrc_basic                                                                      testCaseName = "sql_CreateOrc_basic"
	case_FileFormats_sql_CreateOrc_all                                                                        testCaseName = "sql_CreateOrc_all"
	case_FileFormats_validation_CreateParquet_opts_ConflictingFields_Compression_SnappyCompression            testCaseName = "validation_CreateParquet_opts_ConflictingFields_Compression_SnappyCompression"
	case_FileFormats_validation_CreateParquet_name_ValidIdentifier                                            testCaseName = "validation_CreateParquet_name_ValidIdentifier"
	case_FileFormats_validation_CreateParquet_opts_ConflictingFields_OrReplace_IfNotExists                    testCaseName = "validation_CreateParquet_opts_ConflictingFields_OrReplace_IfNotExists"
	case_FileFormats_sql_CreateParquet_basic                                                                  testCaseName = "sql_CreateParquet_basic"
	case_FileFormats_sql_CreateParquet_all                                                                    testCaseName = "sql_CreateParquet_all"
	case_FileFormats_validation_CreateXml_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters    testCaseName = "validation_CreateXml_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters"
	case_FileFormats_validation_CreateXml_name_ValidIdentifier                                                testCaseName = "validation_CreateXml_name_ValidIdentifier"
	case_FileFormats_validation_CreateXml_opts_ConflictingFields_OrReplace_IfNotExists                        testCaseName = "validation_CreateXml_opts_ConflictingFields_OrReplace_IfNotExists"
	case_FileFormats_sql_CreateXml_basic                                                                      testCaseName = "sql_CreateXml_basic"
	case_FileFormats_sql_CreateXml_all                                                                        testCaseName = "sql_CreateXml_all"
	case_FileFormats_validation_AlterCsv_name_ValidIdentifier                                                 testCaseName = "validation_AlterCsv_name_ValidIdentifier"
	case_FileFormats_validation_AlterCsv_opts_ExactlyOneValueSet_NoneSet                                      testCaseName = "validation_AlterCsv_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_ExactlyOneValueSet_MoreThanOneSet                               testCaseName = "validation_AlterCsv_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_ConflictingFields                                           testCaseName = "validation_AlterCsv_opts_Set_ConflictingFields"
	case_FileFormats_validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_NoneSet                  testCaseName = "validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet           testCaseName = "validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_NoneSet                   testCaseName = "validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet            testCaseName = "validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet                       testCaseName = "validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet                testCaseName = "validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet                       testCaseName = "validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet                testCaseName = "validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet                  testCaseName = "validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet           testCaseName = "validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_NoneSet                           testCaseName = "validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_MoreThanOneSet                    testCaseName = "validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet            testCaseName = "validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet     testCaseName = "validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet        testCaseName = "validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet testCaseName = "validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_AlterCsv_RenameTo                                                                    testCaseName = "sql_AlterCsv_RenameTo"
	case_FileFormats_sql_AlterCsv_Set                                                                         testCaseName = "sql_AlterCsv_Set"
	case_FileFormats_validation_AlterJson_name_ValidIdentifier                                                testCaseName = "validation_AlterJson_name_ValidIdentifier"
	case_FileFormats_validation_AlterJson_opts_ExactlyOneValueSet_NoneSet                                     testCaseName = "validation_AlterJson_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterJson_opts_ExactlyOneValueSet_MoreThanOneSet                              testCaseName = "validation_AlterJson_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterJson_opts_Set_ConflictingFields                                          testCaseName = "validation_AlterJson_opts_Set_ConflictingFields"
	case_FileFormats_validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet                      testCaseName = "validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet               testCaseName = "validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet                      testCaseName = "validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet               testCaseName = "validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet                 testCaseName = "validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet          testCaseName = "validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_AlterJson_RenameTo                                                                   testCaseName = "sql_AlterJson_RenameTo"
	case_FileFormats_sql_AlterJson_Set                                                                        testCaseName = "sql_AlterJson_Set"
	case_FileFormats_validation_AlterAvro_name_ValidIdentifier                                                testCaseName = "validation_AlterAvro_name_ValidIdentifier"
	case_FileFormats_validation_AlterAvro_opts_ExactlyOneValueSet_NoneSet                                     testCaseName = "validation_AlterAvro_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterAvro_opts_ExactlyOneValueSet_MoreThanOneSet                              testCaseName = "validation_AlterAvro_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_AlterAvro_RenameTo                                                                   testCaseName = "sql_AlterAvro_RenameTo"
	case_FileFormats_sql_AlterAvro_Set                                                                        testCaseName = "sql_AlterAvro_Set"
	case_FileFormats_validation_AlterOrc_name_ValidIdentifier                                                 testCaseName = "validation_AlterOrc_name_ValidIdentifier"
	case_FileFormats_validation_AlterOrc_opts_ExactlyOneValueSet_NoneSet                                      testCaseName = "validation_AlterOrc_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterOrc_opts_ExactlyOneValueSet_MoreThanOneSet                               testCaseName = "validation_AlterOrc_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_sql_AlterOrc_RenameTo                                                                    testCaseName = "sql_AlterOrc_RenameTo"
	case_FileFormats_sql_AlterOrc_Set                                                                         testCaseName = "sql_AlterOrc_Set"
	case_FileFormats_validation_AlterParquet_name_ValidIdentifier                                             testCaseName = "validation_AlterParquet_name_ValidIdentifier"
	case_FileFormats_validation_AlterParquet_opts_ExactlyOneValueSet_NoneSet                                  testCaseName = "validation_AlterParquet_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterParquet_opts_ExactlyOneValueSet_MoreThanOneSet                           testCaseName = "validation_AlterParquet_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterParquet_opts_Set_ConflictingFields                                       testCaseName = "validation_AlterParquet_opts_Set_ConflictingFields"
	case_FileFormats_sql_AlterParquet_RenameTo                                                                testCaseName = "sql_AlterParquet_RenameTo"
	case_FileFormats_sql_AlterParquet_Set                                                                     testCaseName = "sql_AlterParquet_Set"
	case_FileFormats_validation_AlterXml_name_ValidIdentifier                                                 testCaseName = "validation_AlterXml_name_ValidIdentifier"
	case_FileFormats_validation_AlterXml_opts_ExactlyOneValueSet_NoneSet                                      testCaseName = "validation_AlterXml_opts_ExactlyOneValueSet_NoneSet"
	case_FileFormats_validation_AlterXml_opts_ExactlyOneValueSet_MoreThanOneSet                               testCaseName = "validation_AlterXml_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_FileFormats_validation_AlterXml_opts_Set_ConflictingFields                                           testCaseName = "validation_AlterXml_opts_Set_ConflictingFields"
	case_FileFormats_sql_AlterXml_RenameTo                                                                    testCaseName = "sql_AlterXml_RenameTo"
	case_FileFormats_sql_AlterXml_Set                                                                         testCaseName = "sql_AlterXml_Set"
	case_FileFormats_validation_Drop_name_ValidIdentifier                                                     testCaseName = "validation_Drop_name_ValidIdentifier"
	case_FileFormats_sql_Drop_basic                                                                           testCaseName = "sql_Drop_basic"
	case_FileFormats_sql_Drop_all                                                                             testCaseName = "sql_Drop_all"
	case_FileFormats_sql_Show_basic                                                                           testCaseName = "sql_Show_basic"
	case_FileFormats_sql_Show_all                                                                             testCaseName = "sql_Show_all"
	case_FileFormats_sql_Show_Like                                                                            testCaseName = "sql_Show_Like"
	case_FileFormats_sql_Show_In                                                                              testCaseName = "sql_Show_In"
	case_FileFormats_validation_Describe_name_ValidIdentifier                                                 testCaseName = "validation_Describe_name_ValidIdentifier"
	case_FileFormats_sql_Describe_basic                                                                       testCaseName = "sql_Describe_basic"
)

type FileFormatsTestsContext struct {
	CreateCsv     *sdkTestCtx[*CreateCsvFileFormatOptions]
	CreateJson    *sdkTestCtx[*CreateJsonFileFormatOptions]
	CreateAvro    *sdkTestCtx[*CreateAvroFileFormatOptions]
	CreateOrc     *sdkTestCtx[*CreateOrcFileFormatOptions]
	CreateParquet *sdkTestCtx[*CreateParquetFileFormatOptions]
	CreateXml     *sdkTestCtx[*CreateXmlFileFormatOptions]
	AlterCsv      *sdkTestCtx[*AlterCsvFileFormatOptions]
	AlterJson     *sdkTestCtx[*AlterJsonFileFormatOptions]
	AlterAvro     *sdkTestCtx[*AlterAvroFileFormatOptions]
	AlterOrc      *sdkTestCtx[*AlterOrcFileFormatOptions]
	AlterParquet  *sdkTestCtx[*AlterParquetFileFormatOptions]
	AlterXml      *sdkTestCtx[*AlterXmlFileFormatOptions]
	Drop          *sdkTestCtx[*DropFileFormatOptions]
	Show          *sdkTestCtx[*ShowFileFormatOptions]
	Describe      *sdkTestCtx[*DescribeFileFormatOptions]
}

var fileFormatsTests = FileFormatsTestsContext{
	CreateCsv: newSdkTestCtx[*CreateCsvFileFormatOptions](
		"FileFormats", "CreateCsv",
	).
		withDefaultOpts(func() *CreateCsvFileFormatOptions {
			return &CreateCsvFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_ConflictingFields_SkipHeader_ParseHeader,
				ExpectedErr: errOneOf("CreateCsvFileFormatOptions", "SkipHeader", "ParseHeader"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.SkipHeader = new(1)
					opts.ParseHeader = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_ConflictingFields_OrReplace_IfNotExists,
				ExpectedErr: errOneOf("CreateCsvFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.RecordDelimiter", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.RecordDelimiter = &StageFileFormatStringOrNone{}
					opts.RecordDelimiter.Value = nil
					opts.RecordDelimiter.None = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.RecordDelimiter", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.RecordDelimiter = &StageFileFormatStringOrNone{}
					opts.RecordDelimiter.Value = new("foo")
					opts.RecordDelimiter.None = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.FieldDelimiter", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.FieldDelimiter = &StageFileFormatStringOrNone{}
					opts.FieldDelimiter.Value = nil
					opts.FieldDelimiter.None = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.FieldDelimiter", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.FieldDelimiter = &StageFileFormatStringOrNone{}
					opts.FieldDelimiter.Value = new("foo")
					opts.FieldDelimiter.None = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.DateFormat = &StageFileFormatStringOrAuto{}
					opts.DateFormat.Value = nil
					opts.DateFormat.Auto = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.DateFormat = &StageFileFormatStringOrAuto{}
					opts.DateFormat.Value = new("foo")
					opts.DateFormat.Auto = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.TimeFormat.Value = nil
					opts.TimeFormat.Auto = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.TimeFormat.Value = new("foo")
					opts.TimeFormat.Auto = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.TimestampFormat.Value = nil
					opts.TimestampFormat.Auto = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.TimestampFormat.Value = new("foo")
					opts.TimestampFormat.Auto = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_Escape_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.Escape", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.Escape = &StageFileFormatStringOrNone{}
					opts.Escape.Value = nil
					opts.Escape.None = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_Escape_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.Escape", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.Escape = &StageFileFormatStringOrNone{}
					opts.Escape.Value = new("foo")
					opts.Escape.None = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.EscapeUnenclosedField", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.EscapeUnenclosedField = &StageFileFormatStringOrNone{}
					opts.EscapeUnenclosedField.Value = nil
					opts.EscapeUnenclosedField.None = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.EscapeUnenclosedField", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.EscapeUnenclosedField = &StageFileFormatStringOrNone{}
					opts.EscapeUnenclosedField.Value = new("foo")
					opts.EscapeUnenclosedField.None = new(true)
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.FieldOptionallyEnclosedBy", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.FieldOptionallyEnclosedBy = &StageFileFormatStringOrNone{}
					opts.FieldOptionallyEnclosedBy.Value = nil
					opts.FieldOptionallyEnclosedBy.None = nil
				},
			},
			validationCase[*CreateCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateCsv_opts_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateCsvFileFormatOptions.FieldOptionallyEnclosedBy", "Value", "None"),
				DefaultModify: func(opts *CreateCsvFileFormatOptions) {
					opts.FieldOptionallyEnclosedBy = &StageFileFormatStringOrNone{}
					opts.FieldOptionallyEnclosedBy.Value = new("foo")
					opts.FieldOptionallyEnclosedBy.None = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateCsvFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateCsv_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateCsvFileFormatOptions]{
				Name: case_FileFormats_sql_CreateCsv_all,
			},
		),
	CreateJson: newSdkTestCtx[*CreateJsonFileFormatOptions](
		"FileFormats", "CreateJson",
	).
		withDefaultOpts(func() *CreateJsonFileFormatOptions {
			return &CreateJsonFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters,
				ExpectedErr: errOneOf("CreateJsonFileFormatOptions", "IgnoreUtf8Errors", "ReplaceInvalidCharacters"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.IgnoreUtf8Errors = new(true)
					opts.ReplaceInvalidCharacters = new(true)
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_ConflictingFields_OrReplace_IfNotExists,
				ExpectedErr: errOneOf("CreateJsonFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.DateFormat = &StageFileFormatStringOrAuto{}
					opts.DateFormat.Value = nil
					opts.DateFormat.Auto = nil
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_DateFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.DateFormat = &StageFileFormatStringOrAuto{}
					opts.DateFormat.Value = new("foo")
					opts.DateFormat.Auto = new(true)
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.TimeFormat.Value = nil
					opts.TimeFormat.Auto = nil
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_TimeFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.TimeFormat.Value = new("foo")
					opts.TimeFormat.Auto = new(true)
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.TimestampFormat.Value = nil
					opts.TimestampFormat.Auto = nil
				},
			},
			validationCase[*CreateJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateJson_opts_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("CreateJsonFileFormatOptions.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *CreateJsonFileFormatOptions) {
					opts.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.TimestampFormat.Value = new("foo")
					opts.TimestampFormat.Auto = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateJsonFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateJson_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateJsonFileFormatOptions]{
				Name: case_FileFormats_sql_CreateJson_all,
			},
		),
	CreateAvro: newSdkTestCtx[*CreateAvroFileFormatOptions](
		"FileFormats", "CreateAvro",
	).
		withDefaultOpts(func() *CreateAvroFileFormatOptions {
			return &CreateAvroFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateAvroFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateAvro_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateAvroFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateAvroFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateAvro_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateAvroFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateAvroFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateAvroFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateAvro_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateAvroFileFormatOptions]{
				Name: case_FileFormats_sql_CreateAvro_all,
			},
		),
	CreateOrc: newSdkTestCtx[*CreateOrcFileFormatOptions](
		"FileFormats", "CreateOrc",
	).
		withDefaultOpts(func() *CreateOrcFileFormatOptions {
			return &CreateOrcFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateOrcFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateOrc_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateOrcFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateOrcFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateOrc_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateOrcFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateOrcFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateOrcFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateOrc_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateOrcFileFormatOptions]{
				Name: case_FileFormats_sql_CreateOrc_all,
			},
		),
	CreateParquet: newSdkTestCtx[*CreateParquetFileFormatOptions](
		"FileFormats", "CreateParquet",
	).
		withDefaultOpts(func() *CreateParquetFileFormatOptions {
			return &CreateParquetFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateParquet_opts_ConflictingFields_Compression_SnappyCompression,
				ExpectedErr: errOneOf("CreateParquetFileFormatOptions", "Compression", "SnappyCompression"),
			},
			validationCase[*CreateParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateParquet_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateParquetFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateParquet_opts_ConflictingFields_OrReplace_IfNotExists,
				ExpectedErr: errOneOf("CreateParquetFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateParquetFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateParquetFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateParquet_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateParquetFileFormatOptions]{
				Name: case_FileFormats_sql_CreateParquet_all,
			},
		),
	CreateXml: newSdkTestCtx[*CreateXmlFileFormatOptions](
		"FileFormats", "CreateXml",
	).
		withDefaultOpts(func() *CreateXmlFileFormatOptions {
			return &CreateXmlFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateXml_opts_ConflictingFields_IgnoreUtf8Errors_ReplaceInvalidCharacters,
				ExpectedErr: errOneOf("CreateXmlFileFormatOptions", "IgnoreUtf8Errors", "ReplaceInvalidCharacters"),
				DefaultModify: func(opts *CreateXmlFileFormatOptions) {
					opts.IgnoreUtf8Errors = new(true)
					opts.ReplaceInvalidCharacters = new(true)
				},
			},
			validationCase[*CreateXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateXml_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateXmlFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_CreateXml_opts_ConflictingFields_OrReplace_IfNotExists,
				ExpectedErr: errOneOf("CreateXmlFileFormatOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreateXmlFileFormatOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateXmlFileFormatOptions]{
				Name:           case_FileFormats_sql_CreateXml_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateXmlFileFormatOptions]{
				Name: case_FileFormats_sql_CreateXml_all,
			},
		),
	AlterCsv: newSdkTestCtx[*AlterCsvFileFormatOptions](
		"FileFormats", "AlterCsv",
	).
		withDefaultOpts(func() *AlterCsvFileFormatOptions {
			return &AlterCsvFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterCsvFileFormatSet{}
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_ConflictingFields,
				ExpectedErr: errOneOf("AlterCsvFileFormatOptions.Set", "SkipHeader", "ParseHeader"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.SkipHeader = new(1)
					opts.Set.ParseHeader = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.RecordDelimiter", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.RecordDelimiter = &StageFileFormatStringOrNone{}
					opts.Set.RecordDelimiter.Value = nil
					opts.Set.RecordDelimiter.None = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_RecordDelimiter_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.RecordDelimiter", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.RecordDelimiter = &StageFileFormatStringOrNone{}
					opts.Set.RecordDelimiter.Value = new("foo")
					opts.Set.RecordDelimiter.None = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.FieldDelimiter", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.FieldDelimiter = &StageFileFormatStringOrNone{}
					opts.Set.FieldDelimiter.Value = nil
					opts.Set.FieldDelimiter.None = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_FieldDelimiter_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.FieldDelimiter", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.FieldDelimiter = &StageFileFormatStringOrNone{}
					opts.Set.FieldDelimiter.Value = new("foo")
					opts.Set.FieldDelimiter.None = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.DateFormat = &StageFileFormatStringOrAuto{}
					opts.Set.DateFormat.Value = nil
					opts.Set.DateFormat.Auto = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.DateFormat = &StageFileFormatStringOrAuto{}
					opts.Set.DateFormat.Value = new("foo")
					opts.Set.DateFormat.Auto = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimeFormat.Value = nil
					opts.Set.TimeFormat.Auto = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimeFormat.Value = new("foo")
					opts.Set.TimeFormat.Auto = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimestampFormat.Value = nil
					opts.Set.TimestampFormat.Auto = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimestampFormat.Value = new("foo")
					opts.Set.TimestampFormat.Auto = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.Escape", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.Escape = &StageFileFormatStringOrNone{}
					opts.Set.Escape.Value = nil
					opts.Set.Escape.None = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_Escape_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.Escape", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.Escape = &StageFileFormatStringOrNone{}
					opts.Set.Escape.Value = new("foo")
					opts.Set.Escape.None = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.EscapeUnenclosedField", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.EscapeUnenclosedField = &StageFileFormatStringOrNone{}
					opts.Set.EscapeUnenclosedField.Value = nil
					opts.Set.EscapeUnenclosedField.None = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_EscapeUnenclosedField_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.EscapeUnenclosedField", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.EscapeUnenclosedField = &StageFileFormatStringOrNone{}
					opts.Set.EscapeUnenclosedField.Value = new("foo")
					opts.Set.EscapeUnenclosedField.None = new(true)
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.FieldOptionallyEnclosedBy", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.FieldOptionallyEnclosedBy = &StageFileFormatStringOrNone{}
					opts.Set.FieldOptionallyEnclosedBy.Value = nil
					opts.Set.FieldOptionallyEnclosedBy.None = nil
				},
			},
			validationCase[*AlterCsvFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterCsv_opts_Set_FieldOptionallyEnclosedBy_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterCsvFileFormatOptions.Set.FieldOptionallyEnclosedBy", "Value", "None"),
				DefaultModify: func(opts *AlterCsvFileFormatOptions) {
					opts.Set = &AlterCsvFileFormatSet{}
					opts.Set.FieldOptionallyEnclosedBy = &StageFileFormatStringOrNone{}
					opts.Set.FieldOptionallyEnclosedBy.Value = new("foo")
					opts.Set.FieldOptionallyEnclosedBy.None = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterCsvFileFormatOptions]{
				Name: case_FileFormats_sql_AlterCsv_RenameTo,
			},
			sqlCase[*AlterCsvFileFormatOptions]{
				Name: case_FileFormats_sql_AlterCsv_Set,
			},
		),
	AlterJson: newSdkTestCtx[*AlterJsonFileFormatOptions](
		"FileFormats", "AlterJson",
	).
		withDefaultOpts(func() *AlterJsonFileFormatOptions {
			return &AlterJsonFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterJsonFileFormatSet{}
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_ConflictingFields,
				ExpectedErr: errOneOf("AlterJsonFileFormatOptions.Set", "IgnoreUtf8Errors", "ReplaceInvalidCharacters"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.IgnoreUtf8Errors = new(true)
					opts.Set.ReplaceInvalidCharacters = new(true)
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.DateFormat = &StageFileFormatStringOrAuto{}
					opts.Set.DateFormat.Value = nil
					opts.Set.DateFormat.Auto = nil
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_DateFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.DateFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.DateFormat = &StageFileFormatStringOrAuto{}
					opts.Set.DateFormat.Value = new("foo")
					opts.Set.DateFormat.Auto = new(true)
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimeFormat.Value = nil
					opts.Set.TimeFormat.Auto = nil
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_TimeFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.TimeFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.TimeFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimeFormat.Value = new("foo")
					opts.Set.TimeFormat.Auto = new(true)
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimestampFormat.Value = nil
					opts.Set.TimestampFormat.Auto = nil
				},
			},
			validationCase[*AlterJsonFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterJson_opts_Set_TimestampFormat_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterJsonFileFormatOptions.Set.TimestampFormat", "Value", "Auto"),
				DefaultModify: func(opts *AlterJsonFileFormatOptions) {
					opts.Set = &AlterJsonFileFormatSet{}
					opts.Set.TimestampFormat = &StageFileFormatStringOrAuto{}
					opts.Set.TimestampFormat.Value = new("foo")
					opts.Set.TimestampFormat.Auto = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterJsonFileFormatOptions]{
				Name: case_FileFormats_sql_AlterJson_RenameTo,
			},
			sqlCase[*AlterJsonFileFormatOptions]{
				Name: case_FileFormats_sql_AlterJson_Set,
			},
		),
	AlterAvro: newSdkTestCtx[*AlterAvroFileFormatOptions](
		"FileFormats", "AlterAvro",
	).
		withDefaultOpts(func() *AlterAvroFileFormatOptions {
			return &AlterAvroFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterAvroFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterAvro_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterAvroFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterAvroFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterAvro_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterAvroFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterAvroFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterAvroFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterAvro_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterAvroFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterAvroFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterAvroFileFormatSet{}
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterAvroFileFormatOptions]{
				Name: case_FileFormats_sql_AlterAvro_RenameTo,
			},
			sqlCase[*AlterAvroFileFormatOptions]{
				Name: case_FileFormats_sql_AlterAvro_Set,
			},
		),
	AlterOrc: newSdkTestCtx[*AlterOrcFileFormatOptions](
		"FileFormats", "AlterOrc",
	).
		withDefaultOpts(func() *AlterOrcFileFormatOptions {
			return &AlterOrcFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterOrcFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterOrc_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterOrcFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterOrcFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterOrc_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterOrcFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterOrcFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterOrcFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterOrc_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterOrcFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterOrcFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterOrcFileFormatSet{}
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterOrcFileFormatOptions]{
				Name: case_FileFormats_sql_AlterOrc_RenameTo,
			},
			sqlCase[*AlterOrcFileFormatOptions]{
				Name: case_FileFormats_sql_AlterOrc_Set,
			},
		),
	AlterParquet: newSdkTestCtx[*AlterParquetFileFormatOptions](
		"FileFormats", "AlterParquet",
	).
		withDefaultOpts(func() *AlterParquetFileFormatOptions {
			return &AlterParquetFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterParquet_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterParquetFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterParquet_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterParquetFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterParquetFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterParquet_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterParquetFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterParquetFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterParquetFileFormatSet{}
				},
			},
			validationCase[*AlterParquetFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterParquet_opts_Set_ConflictingFields,
				ExpectedErr: errOneOf("AlterParquetFileFormatOptions.Set", "Compression", "SnappyCompression"),
			},
		).
		withSqlCases(
			sqlCase[*AlterParquetFileFormatOptions]{
				Name: case_FileFormats_sql_AlterParquet_RenameTo,
			},
			sqlCase[*AlterParquetFileFormatOptions]{
				Name: case_FileFormats_sql_AlterParquet_Set,
			},
		),
	AlterXml: newSdkTestCtx[*AlterXmlFileFormatOptions](
		"FileFormats", "AlterXml",
	).
		withDefaultOpts(func() *AlterXmlFileFormatOptions {
			return &AlterXmlFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterXml_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterXmlFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterXml_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterXmlFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterXmlFileFormatOptions) {
					opts.RenameTo = nil
					opts.Set = nil
				},
			},
			validationCase[*AlterXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterXml_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterXmlFileFormatOptions", "RenameTo", "Set"),
				DefaultModify: func(opts *AlterXmlFileFormatOptions) {
					opts.RenameTo = new(randomSchemaObjectIdentifier())
					opts.Set = &AlterXmlFileFormatSet{}
				},
			},
			validationCase[*AlterXmlFileFormatOptions]{
				Name:        case_FileFormats_validation_AlterXml_opts_Set_ConflictingFields,
				ExpectedErr: errOneOf("AlterXmlFileFormatOptions.Set", "IgnoreUtf8Errors", "ReplaceInvalidCharacters"),
				DefaultModify: func(opts *AlterXmlFileFormatOptions) {
					opts.Set = &AlterXmlFileFormatSet{}
					opts.Set.IgnoreUtf8Errors = new(true)
					opts.Set.ReplaceInvalidCharacters = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterXmlFileFormatOptions]{
				Name: case_FileFormats_sql_AlterXml_RenameTo,
			},
			sqlCase[*AlterXmlFileFormatOptions]{
				Name: case_FileFormats_sql_AlterXml_Set,
			},
		),
	Drop: newSdkTestCtx[*DropFileFormatOptions](
		"FileFormats", "Drop",
	).
		withDefaultOpts(func() *DropFileFormatOptions {
			return &DropFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropFileFormatOptions]{
				Name:        case_FileFormats_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DropFileFormatOptions]{
				Name:           case_FileFormats_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropFileFormatOptions]{
				Name: case_FileFormats_sql_Drop_all,
			},
		),
	Show: newSdkTestCtx[*ShowFileFormatOptions](
		"FileFormats", "Show",
	).
		withDefaultOpts(func() *ShowFileFormatOptions {
			return &ShowFileFormatOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowFileFormatOptions]{
				Name:           case_FileFormats_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowFileFormatOptions]{
				Name: case_FileFormats_sql_Show_all,
			},
			sqlCase[*ShowFileFormatOptions]{
				Name: case_FileFormats_sql_Show_Like,
			},
			sqlCase[*ShowFileFormatOptions]{
				Name: case_FileFormats_sql_Show_In,
			},
		),
	Describe: newSdkTestCtx[*DescribeFileFormatOptions](
		"FileFormats", "Describe",
	).
		withDefaultOpts(func() *DescribeFileFormatOptions {
			return &DescribeFileFormatOptions{
				name: fileFormatsTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DescribeFileFormatOptions]{
				Name:        case_FileFormats_validation_Describe_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DescribeFileFormatOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DescribeFileFormatOptions]{
				Name:           case_FileFormats_sql_Describe_basic,
				NoModifyNeeded: true,
			},
		),
}

func TestFileFormats_CreateCsv(t *testing.T) {
	fileFormatsTests.CreateCsv.RunValidationCases(t)
	fileFormatsTests.CreateCsv.RunSqlCases(t)
}

func TestFileFormats_CreateJson(t *testing.T) {
	fileFormatsTests.CreateJson.RunValidationCases(t)
	fileFormatsTests.CreateJson.RunSqlCases(t)
}

func TestFileFormats_CreateAvro(t *testing.T) {
	fileFormatsTests.CreateAvro.RunValidationCases(t)
	fileFormatsTests.CreateAvro.RunSqlCases(t)
}

func TestFileFormats_CreateOrc(t *testing.T) {
	fileFormatsTests.CreateOrc.RunValidationCases(t)
	fileFormatsTests.CreateOrc.RunSqlCases(t)
}

func TestFileFormats_CreateParquet(t *testing.T) {
	fileFormatsTests.CreateParquet.RunValidationCases(t)
	fileFormatsTests.CreateParquet.RunSqlCases(t)
}

func TestFileFormats_CreateXml(t *testing.T) {
	fileFormatsTests.CreateXml.RunValidationCases(t)
	fileFormatsTests.CreateXml.RunSqlCases(t)
}

func TestFileFormats_AlterCsv(t *testing.T) {
	fileFormatsTests.AlterCsv.RunValidationCases(t)
	fileFormatsTests.AlterCsv.RunSqlCases(t)
}

func TestFileFormats_AlterJson(t *testing.T) {
	fileFormatsTests.AlterJson.RunValidationCases(t)
	fileFormatsTests.AlterJson.RunSqlCases(t)
}

func TestFileFormats_AlterAvro(t *testing.T) {
	fileFormatsTests.AlterAvro.RunValidationCases(t)
	fileFormatsTests.AlterAvro.RunSqlCases(t)
}

func TestFileFormats_AlterOrc(t *testing.T) {
	fileFormatsTests.AlterOrc.RunValidationCases(t)
	fileFormatsTests.AlterOrc.RunSqlCases(t)
}

func TestFileFormats_AlterParquet(t *testing.T) {
	fileFormatsTests.AlterParquet.RunValidationCases(t)
	fileFormatsTests.AlterParquet.RunSqlCases(t)
}

func TestFileFormats_AlterXml(t *testing.T) {
	fileFormatsTests.AlterXml.RunValidationCases(t)
	fileFormatsTests.AlterXml.RunSqlCases(t)
}

func TestFileFormats_Drop(t *testing.T) {
	fileFormatsTests.Drop.RunValidationCases(t)
	fileFormatsTests.Drop.RunSqlCases(t)
}

func TestFileFormats_Show(t *testing.T) {
	fileFormatsTests.Show.RunValidationCases(t)
	fileFormatsTests.Show.RunSqlCases(t)
}

func TestFileFormats_Describe(t *testing.T) {
	fileFormatsTests.Describe.RunValidationCases(t)
	fileFormatsTests.Describe.RunSqlCases(t)
}
