// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"context"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/collections"
)

var (
	_ HybridTables                       = (*hybridTables)(nil)
	_ convertibleRow[HybridTable]        = new(hybridTableRow)
	_ convertibleRow[HybridTableDetails] = new(hybridTableDetailsRow)
	_ convertibleRow[HybridTableIndex]   = new(hybridTableIndexRow)
	_ convertibleRow[TablePrimaryKey]    = new(tablePrimaryKeyRow)
	_ convertibleRow[TableUniqueKey]     = new(tableUniqueKeyRow)
	_ convertibleRow[TableImportedKey]   = new(tableImportedKeyRow)
)

type hybridTables struct {
	client *Client
}

func (v *hybridTables) Create(ctx context.Context, request *CreateHybridTableRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *hybridTables) Alter(ctx context.Context, request *AlterHybridTableRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *hybridTables) Drop(ctx context.Context, request *DropHybridTableRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *hybridTables) DropSafely(ctx context.Context, id SchemaObjectIdentifier) error {
	return SafeDrop(v.client, func() error { return v.Drop(ctx, NewDropHybridTableRequest(id).WithIfExists(true)) }, ctx, id)
}

func (v *hybridTables) Show(ctx context.Context, request *ShowHybridTableRequest) ([]HybridTable, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[hybridTableRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[hybridTableRow, HybridTable](dbRows)
}

func (v *hybridTables) ShowByID(ctx context.Context, id SchemaObjectIdentifier) (*HybridTable, error) {
	request := NewShowHybridTableRequest().
		WithLike(Like{Pattern: String(id.Name())}).
		WithIn(In{Schema: id.SchemaId()})
	hybridTables, err := v.Show(ctx, request)
	if err != nil {
		return nil, err
	}
	return collections.FindFirst(hybridTables, func(r HybridTable) bool { return r.Name == id.Name() })
}

func (v *hybridTables) ShowByIDSafely(ctx context.Context, id SchemaObjectIdentifier) (*HybridTable, error) {
	return SafeShowById(v.client, v.ShowByID, ctx, id)
}

func (v *hybridTables) Describe(ctx context.Context, id SchemaObjectIdentifier) ([]HybridTableDetails, error) {
	opts := &DescribeHybridTableOptions{
		name: id,
	}
	rows, err := validateAndQuery[hybridTableDetailsRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[hybridTableDetailsRow, HybridTableDetails](rows)
}

func (v *hybridTables) CreateIndex(ctx context.Context, request *CreateIndexHybridTableRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *hybridTables) DropIndex(ctx context.Context, request *DropIndexHybridTableRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *hybridTables) ShowIndexes(ctx context.Context, request *ShowIndexesHybridTableRequest) ([]HybridTableIndex, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[hybridTableIndexRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[hybridTableIndexRow, HybridTableIndex](dbRows)
}

func (v *hybridTables) ShowPrimaryKeys(ctx context.Context, request *ShowPrimaryKeysHybridTableRequest) ([]TablePrimaryKey, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[tablePrimaryKeyRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[tablePrimaryKeyRow, TablePrimaryKey](dbRows)
}

func (v *hybridTables) ShowUniqueKeys(ctx context.Context, request *ShowUniqueKeysHybridTableRequest) ([]TableUniqueKey, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[tableUniqueKeyRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[tableUniqueKeyRow, TableUniqueKey](dbRows)
}

func (v *hybridTables) ShowImportedKeys(ctx context.Context, request *ShowImportedKeysHybridTableRequest) ([]TableImportedKey, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[tableImportedKeyRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[tableImportedKeyRow, TableImportedKey](dbRows)
}

func (r *CreateHybridTableRequest) toOpts() *CreateHybridTableOptions {
	opts := &CreateHybridTableOptions{
		OrReplace:                  r.OrReplace,
		IfNotExists:                r.IfNotExists,
		name:                       r.name,
		DataRetentionTimeInDays:    r.DataRetentionTimeInDays,
		MaxDataExtensionTimeInDays: r.MaxDataExtensionTimeInDays,
		Comment:                    r.Comment,
	}
	opts.ColumnsAndConstraints = HybridTableColumnsConstraintsAndIndexes{}
	if r.ColumnsAndConstraints.Columns != nil {
		columns := make([]HybridTableColumn, len(r.ColumnsAndConstraints.Columns))
		for i, v := range r.ColumnsAndConstraints.Columns {
			columns[i] = HybridTableColumn{
				Name:             v.Name,
				DataType:         v.DataType,
				InlineConstraint: v.InlineConstraint,
				NotNull:          v.NotNull,
				DefaultValue:     v.DefaultValue,
				Collate:          v.Collate,
				Comment:          v.Comment,
			}
		}
		opts.ColumnsAndConstraints.Columns = columns
	}
	if r.ColumnsAndConstraints.OutOfLineConstraint != nil {
		outOfLineConstraint := make([]HybridTableOutOfLineConstraint, len(r.ColumnsAndConstraints.OutOfLineConstraint))
		for i, v := range r.ColumnsAndConstraints.OutOfLineConstraint {
			outOfLineConstraint[i] = HybridTableOutOfLineConstraint{
				Name:                 v.Name,
				ColumnConstraintType: v.ColumnConstraintType,
				Columns:              v.Columns,
			}
			if v.ForeignKey != nil {
				outOfLineConstraint[i].ForeignKey = &HybridTableOutOfLineForeignKey{
					TableName:   v.ForeignKey.TableName,
					ColumnNames: v.ForeignKey.ColumnNames,
					Match:       v.ForeignKey.Match,
					On:          v.ForeignKey.On,
				}
			}
		}
		opts.ColumnsAndConstraints.OutOfLineConstraint = outOfLineConstraint
	}
	if r.ColumnsAndConstraints.OutOfLineIndex != nil {
		outOfLineIndex := make([]HybridTableOutOfLineIndex, len(r.ColumnsAndConstraints.OutOfLineIndex))
		for i, v := range r.ColumnsAndConstraints.OutOfLineIndex {
			outOfLineIndex[i] = HybridTableOutOfLineIndex{
				Name:           v.Name,
				Columns:        v.Columns,
				IncludeColumns: v.IncludeColumns,
			}
		}
		opts.ColumnsAndConstraints.OutOfLineIndex = outOfLineIndex
	}
	return opts
}

func (r *AlterHybridTableRequest) toOpts() *AlterHybridTableOptions {
	opts := &AlterHybridTableOptions{
		IfExists: r.IfExists,
		name:     r.name,
		RenameTo: r.RenameTo,
	}
	if r.AddColumnAction != nil {
		opts.AddColumnAction = &HybridTableAddColumnAction{
			IfNotExists:      r.AddColumnAction.IfNotExists,
			Name:             r.AddColumnAction.Name,
			DataType:         r.AddColumnAction.DataType,
			Collate:          r.AddColumnAction.Collate,
			DefaultValue:     r.AddColumnAction.DefaultValue,
			InlineConstraint: r.AddColumnAction.InlineConstraint,
			Comment:          r.AddColumnAction.Comment,
		}
	}
	if r.ConstraintAction != nil {
		opts.ConstraintAction = &HybridTableConstraintAction{}
		if r.ConstraintAction.Rename != nil {
			opts.ConstraintAction.Rename = &HybridTableConstraintActionRename{
				OldName: r.ConstraintAction.Rename.OldName,
				NewName: r.ConstraintAction.Rename.NewName,
			}
		}
		if r.ConstraintAction.Drop != nil {
			opts.ConstraintAction.Drop = &HybridTableConstraintActionDrop{
				ConstraintName: r.ConstraintAction.Drop.ConstraintName,
				Unique:         r.ConstraintAction.Drop.Unique,
				ForeignKey:     r.ConstraintAction.Drop.ForeignKey,
				Columns:        r.ConstraintAction.Drop.Columns,
				Cascade:        r.ConstraintAction.Drop.Cascade,
				Restrict:       r.ConstraintAction.Drop.Restrict,
			}
		}
	}
	if r.AlterColumnAction != nil {
		alterColumnAction := make([]HybridTableAlterColumnAction, len(r.AlterColumnAction))
		for i, v := range r.AlterColumnAction {
			alterColumnAction[i] = HybridTableAlterColumnAction{
				ColumnName:   v.ColumnName,
				DropDefault:  v.DropDefault,
				SetDefault:   v.SetDefault,
				DataType:     v.DataType,
				Comment:      v.Comment,
				UnsetComment: v.UnsetComment,
			}
		}
		opts.AlterColumnAction = alterColumnAction
	}
	if r.DropColumnAction != nil {
		opts.DropColumnAction = &HybridTableDropColumnAction{
			IfExists: r.DropColumnAction.IfExists,
			Columns:  r.DropColumnAction.Columns,
		}
	}
	if r.DropIndexAction != nil {
		opts.DropIndexAction = &HybridTableDropIndexAction{
			IfExists:  r.DropIndexAction.IfExists,
			IndexName: r.DropIndexAction.IndexName,
		}
	}
	if r.ClusteringAction != nil {
		opts.ClusteringAction = &HybridTableClusteringAction{
			ClusterBy:         r.ClusteringAction.ClusterBy,
			DropClusteringKey: r.ClusteringAction.DropClusteringKey,
		}
		if r.ClusteringAction.Recluster != nil {
			opts.ClusteringAction.Recluster = &HybridTableReclusterAction{
				MaxSize: r.ClusteringAction.Recluster.MaxSize,
				Where:   r.ClusteringAction.Recluster.Where,
			}
		}
		if r.ClusteringAction.ChangeReclusterState != nil {
			opts.ClusteringAction.ChangeReclusterState = &HybridTableReclusterChangeState{
				State: r.ClusteringAction.ChangeReclusterState.State,
			}
		}
	}
	if r.Set != nil {
		opts.Set = &HybridTableSetProperties{
			DataRetentionTimeInDays:    r.Set.DataRetentionTimeInDays,
			MaxDataExtensionTimeInDays: r.Set.MaxDataExtensionTimeInDays,
			Comment:                    r.Set.Comment,
		}
	}
	if r.Unset != nil {
		opts.Unset = &HybridTableUnsetProperties{
			Comment:                    r.Unset.Comment,
			DataRetentionTimeInDays:    r.Unset.DataRetentionTimeInDays,
			MaxDataExtensionTimeInDays: r.Unset.MaxDataExtensionTimeInDays,
		}
	}
	return opts
}

func (r *DropHybridTableRequest) toOpts() *DropHybridTableOptions {
	opts := &DropHybridTableOptions{
		IfExists: r.IfExists,
		name:     r.name,
		Cascade:  r.Cascade,
		Restrict: r.Restrict,
	}
	return opts
}

func (r *ShowHybridTableRequest) toOpts() *ShowHybridTableOptions {
	opts := &ShowHybridTableOptions{
		Terse:      r.Terse,
		Like:       r.Like,
		In:         r.In,
		StartsWith: r.StartsWith,
		Limit:      r.Limit,
	}
	return opts
}

func (r hybridTableRow) convert() (*HybridTable, error) {
	result := &HybridTable{
		CreatedOn:    r.CreatedOn,
		Name:         r.Name,
		DatabaseName: r.DatabaseName,
		SchemaName:   r.SchemaName,
	}
	mapNullStringToNonNullableField(&result.Owner, r.Owner)
	mapNullInt(&result.Rows, r.Rows)
	mapNullInt(&result.Bytes, r.Bytes)
	mapNullStringToNonNullableField(&result.Comment, r.Comment)
	mapNullStringToNonNullableField(&result.OwnerRoleType, r.OwnerRoleType)
	return result, nil
}

func (r *DescribeHybridTableRequest) toOpts() *DescribeHybridTableOptions {
	opts := &DescribeHybridTableOptions{
		name: r.name,
	}
	return opts
}

func (r hybridTableDetailsRow) convert() (*HybridTableDetails, error) {
	result := &HybridTableDetails{
		Name:       r.Name,
		Kind:       r.Kind,
		IsNullable: r.Null == "Y",
		PrimaryKey: r.PrimaryKey == "Y",
		UniqueKey:  r.UniqueKey == "Y",
	}
	mapNullStringToNonNullableField(&result.Default, r.Default)
	mapNullStringToNonNullableField(&result.Check, r.Check)
	mapNullStringToNonNullableField(&result.Expression, r.Expression)
	mapNullStringToNonNullableField(&result.Comment, r.Comment)
	mapNullStringToNonNullableField(&result.PolicyName, r.PolicyName)
	mapNullStringToNonNullableField(&result.PrivacyDomain, r.PrivacyDomain)
	mapNullStringToNonNullableField(&result.SchemaEvolutionRecord, r.SchemaEvolutionRecord)
	if err := r.additionalConvert(result); err != nil {
		return nil, err
	}
	return result, nil
}

func (r *CreateIndexHybridTableRequest) toOpts() *CreateIndexHybridTableOptions {
	opts := &CreateIndexHybridTableOptions{
		OrReplace:      r.OrReplace,
		IfNotExists:    r.IfNotExists,
		name:           r.name,
		TableName:      r.TableName,
		Columns:        r.Columns,
		IncludeColumns: r.IncludeColumns,
	}
	return opts
}

func (r *DropIndexHybridTableRequest) toOpts() *DropIndexHybridTableOptions {
	opts := &DropIndexHybridTableOptions{
		IfExists: r.IfExists,
		name:     r.name,
	}
	return opts
}

func (r *ShowIndexesHybridTableRequest) toOpts() *ShowIndexesHybridTableOptions {
	opts := &ShowIndexesHybridTableOptions{
		Like:       r.Like,
		In:         r.In,
		StartsWith: r.StartsWith,
		Limit:      r.Limit,
	}
	return opts
}

func (r hybridTableIndexRow) convert() (*HybridTableIndex, error) {
	result := &HybridTableIndex{
		CreatedOn:    r.CreatedOn,
		Name:         r.Name,
		TableName:    r.Table,
		DatabaseName: r.DatabaseName,
		SchemaName:   r.SchemaName,
	}
	mapNullStringToBool(&result.IsUnique, r.IsUnique)
	mapNullString(&result.Columns, r.Columns)
	mapNullStringToNonNullableField(&result.IncludedColumns, r.IncludedColumns)
	mapNullStringToNonNullableField(&result.Owner, r.Owner)
	mapNullStringToNonNullableField(&result.OwnerRoleType, r.OwnerRoleType)
	return result, nil
}

func (r *ShowPrimaryKeysHybridTableRequest) toOpts() *ShowPrimaryKeysHybridTableOptions {
	opts := &ShowPrimaryKeysHybridTableOptions{
		name: r.name,
	}
	return opts
}

func (r tablePrimaryKeyRow) convert() (*TablePrimaryKey, error) {
	result := &TablePrimaryKey{
		ConstraintName: r.ConstraintName,
		ColumnName:     r.ColumnName,
		KeySequence:    r.KeySequence,
	}
	return result, nil
}

func (r *ShowUniqueKeysHybridTableRequest) toOpts() *ShowUniqueKeysHybridTableOptions {
	opts := &ShowUniqueKeysHybridTableOptions{
		name: r.name,
	}
	return opts
}

func (r tableUniqueKeyRow) convert() (*TableUniqueKey, error) {
	result := &TableUniqueKey{
		ConstraintName: r.ConstraintName,
		ColumnName:     r.ColumnName,
		KeySequence:    r.KeySequence,
	}
	return result, nil
}

func (r *ShowImportedKeysHybridTableRequest) toOpts() *ShowImportedKeysHybridTableOptions {
	opts := &ShowImportedKeysHybridTableOptions{
		name: r.name,
	}
	return opts
}

func (r tableImportedKeyRow) convert() (*TableImportedKey, error) {
	result := &TableImportedKey{
		FkName:         r.FkName,
		FkColumnName:   r.FkColumnName,
		KeySequence:    r.KeySequence,
		PkDatabaseName: r.PkDatabaseName,
		PkSchemaName:   r.PkSchemaName,
		PkTableName:    r.PkTableName,
		PkColumnName:   r.PkColumnName,
		DeleteRule:     r.DeleteRule,
		UpdateRule:     r.UpdateRule,
	}
	return result, nil
}
