// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

var notebooksTestIdSchemaObjectIdentifier = randomSchemaObjectIdentifier()

const (
	case_Notebooks_validation_Create_name_ValidIdentifier                   testCaseName = "validation_Create_name_ValidIdentifier"
	case_Notebooks_validation_Create_QueryWarehouse_ValidIdentifierIfSet    testCaseName = "validation_Create_QueryWarehouse_ValidIdentifierIfSet"
	case_Notebooks_validation_Create_Warehouse_ValidIdentifierIfSet         testCaseName = "validation_Create_Warehouse_ValidIdentifierIfSet"
	case_Notebooks_validation_Create_opts_ConflictingFields                 testCaseName = "validation_Create_opts_ConflictingFields"
	case_Notebooks_validation_Create_ComputePool_ValidIdentifierIfSet       testCaseName = "validation_Create_ComputePool_ValidIdentifierIfSet"
	case_Notebooks_sql_Create_basic                                         testCaseName = "sql_Create_basic"
	case_Notebooks_sql_Create_all                                           testCaseName = "sql_Create_all"
	case_Notebooks_validation_Alter_name_ValidIdentifier                    testCaseName = "validation_Alter_name_ValidIdentifier"
	case_Notebooks_validation_Alter_RenameTo_ValidIdentifierIfSet           testCaseName = "validation_Alter_RenameTo_ValidIdentifierIfSet"
	case_Notebooks_validation_Alter_opts_ExactlyOneValueSet_NoneSet         testCaseName = "validation_Alter_opts_ExactlyOneValueSet_NoneSet"
	case_Notebooks_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet  testCaseName = "validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_Notebooks_validation_Alter_Set_QueryWarehouse_ValidIdentifierIfSet testCaseName = "validation_Alter_Set_QueryWarehouse_ValidIdentifierIfSet"
	case_Notebooks_validation_Alter_Set_Warehouse_ValidIdentifierIfSet      testCaseName = "validation_Alter_Set_Warehouse_ValidIdentifierIfSet"
	case_Notebooks_validation_Alter_Set_ComputePool_ValidIdentifierIfSet    testCaseName = "validation_Alter_Set_ComputePool_ValidIdentifierIfSet"
	case_Notebooks_validation_Alter_opts_Set_AtLeastOneValueSet             testCaseName = "validation_Alter_opts_Set_AtLeastOneValueSet"
	case_Notebooks_validation_Alter_opts_Unset_AtLeastOneValueSet           testCaseName = "validation_Alter_opts_Unset_AtLeastOneValueSet"
	case_Notebooks_sql_Alter_Set                                            testCaseName = "sql_Alter_Set"
	case_Notebooks_sql_Alter_Unset                                          testCaseName = "sql_Alter_Unset"
	case_Notebooks_sql_Alter_SetTags                                        testCaseName = "sql_Alter_SetTags"
	case_Notebooks_sql_Alter_UnsetTags                                      testCaseName = "sql_Alter_UnsetTags"
	case_Notebooks_sql_Alter_RenameTo                                       testCaseName = "sql_Alter_RenameTo"
	case_Notebooks_validation_Drop_name_ValidIdentifier                     testCaseName = "validation_Drop_name_ValidIdentifier"
	case_Notebooks_sql_Drop_basic                                           testCaseName = "sql_Drop_basic"
	case_Notebooks_sql_Drop_all                                             testCaseName = "sql_Drop_all"
	case_Notebooks_validation_Describe_name_ValidIdentifier                 testCaseName = "validation_Describe_name_ValidIdentifier"
	case_Notebooks_sql_Describe_basic                                       testCaseName = "sql_Describe_basic"
	case_Notebooks_sql_Show_basic                                           testCaseName = "sql_Show_basic"
	case_Notebooks_sql_Show_all                                             testCaseName = "sql_Show_all"
	case_Notebooks_sql_Show_Like                                            testCaseName = "sql_Show_Like"
	case_Notebooks_sql_Show_In                                              testCaseName = "sql_Show_In"
	case_Notebooks_sql_Show_Limit                                           testCaseName = "sql_Show_Limit"
	case_Notebooks_sql_Show_StartsWith                                      testCaseName = "sql_Show_StartsWith"
)

type NotebooksTestsContext struct {
	Create   *sdkTestCtx[*CreateNotebookOptions]
	Alter    *sdkTestCtx[*AlterNotebookOptions]
	Drop     *sdkTestCtx[*DropNotebookOptions]
	Describe *sdkTestCtx[*DescribeNotebookOptions]
	Show     *sdkTestCtx[*ShowNotebookOptions]
}

var notebooksTests = NotebooksTestsContext{
	Create: newSdkTestCtx[*CreateNotebookOptions](
		"Notebooks", "Create",
	).
		withDefaultOpts(func() *CreateNotebookOptions {
			return &CreateNotebookOptions{
				name: notebooksTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreateNotebookOptions]{
				Name:        case_Notebooks_validation_Create_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateNotebookOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreateNotebookOptions]{
				Name:        case_Notebooks_validation_Create_QueryWarehouse_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateNotebookOptions) {
					opts.QueryWarehouse = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateNotebookOptions]{
				Name:        case_Notebooks_validation_Create_Warehouse_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateNotebookOptions) {
					opts.Warehouse = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*CreateNotebookOptions]{
				Name:        case_Notebooks_validation_Create_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreateNotebookOptions", "IfNotExists", "OrReplace"),
				DefaultModify: func(opts *CreateNotebookOptions) {
					opts.IfNotExists = new(true)
					opts.OrReplace = new(true)
				},
			},
			validationCase[*CreateNotebookOptions]{
				Name:        case_Notebooks_validation_Create_ComputePool_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreateNotebookOptions) {
					opts.ComputePool = new(emptyAccountObjectIdentifier)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreateNotebookOptions]{
				Name:           case_Notebooks_sql_Create_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreateNotebookOptions]{
				Name: case_Notebooks_sql_Create_all,
			},
		),
	Alter: newSdkTestCtx[*AlterNotebookOptions](
		"Notebooks", "Alter",
	).
		withDefaultOpts(func() *AlterNotebookOptions {
			return &AlterNotebookOptions{
				name: notebooksTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_RenameTo_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.RenameTo = new(emptySchemaObjectIdentifier)
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterNotebookOptions", "Set", "Unset", "SetTags", "UnsetTags", "RenameTo"),
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.SetTags = nil
					opts.UnsetTags = nil
					opts.RenameTo = nil
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterNotebookOptions", "Set", "Unset", "SetTags", "UnsetTags", "RenameTo"),
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = &NotebookSet{}
					opts.Unset = &NotebookUnset{}
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_Set_QueryWarehouse_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = &NotebookSet{}
					opts.Set.QueryWarehouse = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_Set_Warehouse_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = &NotebookSet{}
					opts.Set.Warehouse = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_Set_ComputePool_ValidIdentifierIfSet,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = &NotebookSet{}
					opts.Set.ComputePool = new(emptyAccountObjectIdentifier)
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterNotebookOptions.Set", "Comment", "QueryWarehouse", "IdleAutoShutdownTimeSeconds", "Secrets", "MainFile", "Warehouse", "RuntimeName", "ComputePool", "ExternalAccessIntegrations", "RuntimeEnvironmentVersion"),
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Set = &NotebookSet{}
					opts.Set.Comment = nil
					opts.Set.QueryWarehouse = nil
					opts.Set.IdleAutoShutdownTimeSeconds = nil
					opts.Set.Secrets = nil
					opts.Set.MainFile = nil
					opts.Set.Warehouse = nil
					opts.Set.RuntimeName = nil
					opts.Set.ComputePool = nil
					opts.Set.ExternalAccessIntegrations = nil
					opts.Set.RuntimeEnvironmentVersion = nil
				},
			},
			validationCase[*AlterNotebookOptions]{
				Name:        case_Notebooks_validation_Alter_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterNotebookOptions.Unset", "Comment", "QueryWarehouse", "Secrets", "Warehouse", "RuntimeName", "ComputePool", "ExternalAccessIntegrations", "RuntimeEnvironmentVersion"),
				DefaultModify: func(opts *AlterNotebookOptions) {
					opts.Unset = &NotebookUnset{}
					opts.Unset.Comment = nil
					opts.Unset.QueryWarehouse = nil
					opts.Unset.Secrets = nil
					opts.Unset.Warehouse = nil
					opts.Unset.RuntimeName = nil
					opts.Unset.ComputePool = nil
					opts.Unset.ExternalAccessIntegrations = nil
					opts.Unset.RuntimeEnvironmentVersion = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterNotebookOptions]{
				Name: case_Notebooks_sql_Alter_Set,
			},
			sqlCase[*AlterNotebookOptions]{
				Name: case_Notebooks_sql_Alter_Unset,
			},
			sqlCase[*AlterNotebookOptions]{
				Name: case_Notebooks_sql_Alter_SetTags,
			},
			sqlCase[*AlterNotebookOptions]{
				Name: case_Notebooks_sql_Alter_UnsetTags,
			},
			sqlCase[*AlterNotebookOptions]{
				Name: case_Notebooks_sql_Alter_RenameTo,
			},
		),
	Drop: newSdkTestCtx[*DropNotebookOptions](
		"Notebooks", "Drop",
	).
		withDefaultOpts(func() *DropNotebookOptions {
			return &DropNotebookOptions{
				name: notebooksTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropNotebookOptions]{
				Name:        case_Notebooks_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropNotebookOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DropNotebookOptions]{
				Name:           case_Notebooks_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropNotebookOptions]{
				Name: case_Notebooks_sql_Drop_all,
			},
		),
	Describe: newSdkTestCtx[*DescribeNotebookOptions](
		"Notebooks", "Describe",
	).
		withDefaultOpts(func() *DescribeNotebookOptions {
			return &DescribeNotebookOptions{
				name: notebooksTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DescribeNotebookOptions]{
				Name:        case_Notebooks_validation_Describe_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DescribeNotebookOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DescribeNotebookOptions]{
				Name:           case_Notebooks_sql_Describe_basic,
				NoModifyNeeded: true,
			},
		),
	Show: newSdkTestCtx[*ShowNotebookOptions](
		"Notebooks", "Show",
	).
		withDefaultOpts(func() *ShowNotebookOptions {
			return &ShowNotebookOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowNotebookOptions]{
				Name:           case_Notebooks_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowNotebookOptions]{
				Name: case_Notebooks_sql_Show_all,
			},
			sqlCase[*ShowNotebookOptions]{
				Name: case_Notebooks_sql_Show_Like,
			},
			sqlCase[*ShowNotebookOptions]{
				Name: case_Notebooks_sql_Show_In,
			},
			sqlCase[*ShowNotebookOptions]{
				Name: case_Notebooks_sql_Show_Limit,
			},
			sqlCase[*ShowNotebookOptions]{
				Name: case_Notebooks_sql_Show_StartsWith,
			},
		),
}

func TestNotebooks_Create(t *testing.T) {
	notebooksTests.Create.RunValidationCases(t)
	notebooksTests.Create.RunSqlCases(t)
}

func TestNotebooks_Alter(t *testing.T) {
	notebooksTests.Alter.RunValidationCases(t)
	notebooksTests.Alter.RunSqlCases(t)
}

func TestNotebooks_Drop(t *testing.T) {
	notebooksTests.Drop.RunValidationCases(t)
	notebooksTests.Drop.RunSqlCases(t)
}

func TestNotebooks_Describe(t *testing.T) {
	notebooksTests.Describe.RunValidationCases(t)
	notebooksTests.Describe.RunSqlCases(t)
}

func TestNotebooks_Show(t *testing.T) {
	notebooksTests.Show.RunValidationCases(t)
	notebooksTests.Show.RunSqlCases(t)
}
