// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"context"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/internal/collections"
)

var (
	_ OpenflowConnectors                       = (*openflowConnectors)(nil)
	_ convertibleRow[OpenflowConnector]        = new(openflowConnectorRow)
	_ convertibleRow[OpenflowConnectorDetails] = new(openflowConnectorDetailsRow)
	_ convertibleRow[OpenflowConnectorVersion] = new(openflowConnectorVersionRow)
)

type openflowConnectors struct {
	client *Client
}

func (v *openflowConnectors) Create(ctx context.Context, request *CreateOpenflowConnectorRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *openflowConnectors) Alter(ctx context.Context, request *AlterOpenflowConnectorRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *openflowConnectors) Drop(ctx context.Context, request *DropOpenflowConnectorRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *openflowConnectors) DropSafely(ctx context.Context, id SchemaObjectIdentifier) error {
	return SafeDrop(v.client, func() error { return v.Drop(ctx, NewDropOpenflowConnectorRequest(id).WithIfExists(true)) }, ctx, id)
}

func (v *openflowConnectors) Show(ctx context.Context, request *ShowOpenflowConnectorRequest) ([]OpenflowConnector, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[openflowConnectorRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[openflowConnectorRow, OpenflowConnector](dbRows)
}

func (v *openflowConnectors) ShowByID(ctx context.Context, id SchemaObjectIdentifier) (*OpenflowConnector, error) {
	request := NewShowOpenflowConnectorRequest().
		WithIn(In{Schema: id.SchemaId()}).
		WithLike(Like{Pattern: String(id.Name())})
	openflowConnectors, err := v.Show(ctx, request)
	if err != nil {
		return nil, err
	}
	return collections.FindFirst(openflowConnectors, func(r OpenflowConnector) bool { return r.Name == id.Name() })
}

func (v *openflowConnectors) ShowByIDSafely(ctx context.Context, id SchemaObjectIdentifier) (*OpenflowConnector, error) {
	return SafeShowById(v.client, v.ShowByID, ctx, id)
}

func (v *openflowConnectors) Describe(ctx context.Context, id SchemaObjectIdentifier) (*OpenflowConnectorDetails, error) {
	opts := &DescribeOpenflowConnectorOptions{
		name: id,
	}
	result, err := validateAndQueryOne[openflowConnectorDetailsRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return conversionErrorWrapped(result.convert())
}

func (v *openflowConnectors) Execute(ctx context.Context, request *ExecuteOpenflowConnectorRequest) error {
	opts := request.toOpts()
	return validateAndExec(v.client, ctx, opts)
}

func (v *openflowConnectors) ShowVersions(ctx context.Context, request *ShowVersionsOpenflowConnectorRequest) ([]OpenflowConnectorVersion, error) {
	opts := request.toOpts()
	dbRows, err := validateAndQuery[openflowConnectorVersionRow](v.client, ctx, opts)
	if err != nil {
		return nil, err
	}
	return convertRows[openflowConnectorVersionRow, OpenflowConnectorVersion](dbRows)
}

func (r *CreateOpenflowConnectorRequest) toOpts() *CreateOpenflowConnectorOptions {
	opts := &CreateOpenflowConnectorOptions{
		IfNotExists:    r.IfNotExists,
		name:           r.name,
		InRuntime:      r.InRuntime,
		FromDefinition: r.FromDefinition,
		From:           r.From,
		DisplayName:    r.DisplayName,
		Comment:        r.Comment,
	}
	return opts
}

func (r *AlterOpenflowConnectorRequest) toOpts() *AlterOpenflowConnectorOptions {
	opts := &AlterOpenflowConnectorOptions{
		IfExists:       r.IfExists,
		name:           r.name,
		Start:          r.Start,
		Stop:           r.Stop,
		Terminate:      r.Terminate,
		TerminateForce: r.TerminateForce,
		Abort:          r.Abort,
		RenameTo:       r.RenameTo,
		Pull:           r.Pull,
	}
	if r.AddVersion != nil {
		opts.AddVersion = &OpenflowConnectorAddVersion{
			From: r.AddVersion.From,
		}
	}
	if r.AddLiveVersion != nil {
		opts.AddLiveVersion = &OpenflowConnectorAddLiveVersion{
			VersionAlias: r.AddLiveVersion.VersionAlias,
			Comment:      r.AddLiveVersion.Comment,
		}
	}
	if r.Commit != nil {
		opts.Commit = &OpenflowConnectorCommit{
			Comment: r.Commit.Comment,
		}
	}
	if r.Push != nil {
		opts.Push = &OpenflowConnectorPush{
			To:       r.Push.To,
			Username: r.Push.Username,
			Password: r.Push.Password,
			Name:     r.Push.Name,
			Email:    r.Push.Email,
			Comment:  r.Push.Comment,
		}
	}
	if r.Set != nil {
		opts.Set = &OpenflowConnectorSet{
			DisplayName: r.Set.DisplayName,
			Comment:     r.Set.Comment,
		}
		if r.Set.DefaultVersion != nil {
			opts.Set.DefaultVersion = &OpenflowConnectorDefaultVersion{
				First:   r.Set.DefaultVersion.First,
				Last:    r.Set.DefaultVersion.Last,
				Version: r.Set.DefaultVersion.Version,
			}
		}
	}
	if r.Unset != nil {
		opts.Unset = &OpenflowConnectorUnset{
			DisplayName: r.Unset.DisplayName,
			Comment:     r.Unset.Comment,
		}
	}
	return opts
}

func (r *DropOpenflowConnectorRequest) toOpts() *DropOpenflowConnectorOptions {
	opts := &DropOpenflowConnectorOptions{
		IfExists: r.IfExists,
		name:     r.name,
	}
	return opts
}

func (r *ShowOpenflowConnectorRequest) toOpts() *ShowOpenflowConnectorOptions {
	opts := &ShowOpenflowConnectorOptions{
		Like:       r.Like,
		In:         r.In,
		StartsWith: r.StartsWith,
		Limit:      r.Limit,
	}
	return opts
}

func (r openflowConnectorRow) convert() (*OpenflowConnector, error) {
	result := &OpenflowConnector{
		Name:         r.Name,
		Runtime:      r.Runtime,
		DatabaseName: r.DatabaseName,
		SchemaName:   r.SchemaName,
		Owner:        r.Owner,
		CreatedOn:    r.CreatedOn,
		UpdatedOn:    r.UpdatedOn,
	}
	mapStringWithMapping(&result.Status, r.Status, ToOpenflowConnectorStatus)
	mapNullString(&result.ConnectorDefinition, r.ConnectorDefinition)
	mapNullString(&result.DisplayName, r.DisplayName)
	mapNullString(&result.DefaultVersion, r.DefaultVersion)
	mapNullString(&result.DefaultVersionName, r.DefaultVersionName)
	mapNullString(&result.DefaultVersionAlias, r.DefaultVersionAlias)
	mapNullString(&result.DefaultVersionLocationUri, r.DefaultVersionLocationUri)
	mapNullString(&result.DefaultVersionSourceLocationUri, r.DefaultVersionSourceLocationUri)
	mapNullString(&result.LiveVersionLocationUri, r.LiveVersionLocationUri)
	mapNullString(&result.Comment, r.Comment)
	mapNullString(&result.ConnectorUrl, r.ConnectorUrl)
	return result, nil
}

func (r *DescribeOpenflowConnectorRequest) toOpts() *DescribeOpenflowConnectorOptions {
	opts := &DescribeOpenflowConnectorOptions{
		name: r.name,
	}
	return opts
}

func (r openflowConnectorDetailsRow) convert() (*OpenflowConnectorDetails, error) {
	result := &OpenflowConnectorDetails{
		Name:    r.Name,
		Runtime: r.Runtime,
		Owner:   r.Owner,
	}
	mapStringWithMapping(&result.Status, r.Status, ToOpenflowConnectorStatus)
	mapNullString(&result.ConnectorDefinition, r.ConnectorDefinition)
	mapNullString(&result.DisplayName, r.DisplayName)
	mapNullString(&result.Comment, r.Comment)
	mapNullString(&result.DefaultVersion, r.DefaultVersion)
	mapNullString(&result.DefaultVersionName, r.DefaultVersionName)
	mapNullString(&result.DefaultVersionAlias, r.DefaultVersionAlias)
	mapNullString(&result.DefaultVersionLocationUri, r.DefaultVersionLocationUri)
	mapNullString(&result.DefaultVersionSourceLocationUri, r.DefaultVersionSourceLocationUri)
	mapNullString(&result.DefaultVersionGitCommitHash, r.DefaultVersionGitCommitHash)
	mapNullString(&result.LastVersionName, r.LastVersionName)
	mapNullString(&result.LastVersionAlias, r.LastVersionAlias)
	mapNullString(&result.LastVersionLocationUri, r.LastVersionLocationUri)
	mapNullString(&result.LastVersionSourceLocationUri, r.LastVersionSourceLocationUri)
	mapNullString(&result.LastVersionGitCommitHash, r.LastVersionGitCommitHash)
	mapNullString(&result.LiveVersionLocationUri, r.LiveVersionLocationUri)
	mapNullString(&result.ConnectorUrl, r.ConnectorUrl)
	if err := r.additionalConvert(result); err != nil {
		return nil, err
	}
	return result, nil
}

func (r *ExecuteOpenflowConnectorRequest) toOpts() *ExecuteOpenflowConnectorOptions {
	opts := &ExecuteOpenflowConnectorOptions{
		name: r.name,
		From: r.From,
		Step: r.Step,
	}
	return opts
}

func (r *ShowVersionsOpenflowConnectorRequest) toOpts() *ShowVersionsOpenflowConnectorOptions {
	opts := &ShowVersionsOpenflowConnectorOptions{
		name:  r.name,
		Limit: r.Limit,
	}
	return opts
}

func (r openflowConnectorVersionRow) convert() (*OpenflowConnectorVersion, error) {
	result := &OpenflowConnectorVersion{
		CreatedOn:   r.CreatedOn,
		IsDefault:   r.IsDefault,
		IsFirst:     r.IsFirst,
		IsLast:      r.IsLast,
		IsLive:      r.IsLive,
		LocationUri: r.LocationUri,
	}
	mapNullString(&result.Name, r.Name)
	mapNullString(&result.Alias, r.Alias)
	mapNullString(&result.Comment, r.Comment)
	mapNullString(&result.SourceLocationUri, r.SourceLocationUri)
	mapNullString(&result.GitCommitHash, r.GitCommitHash)
	return result, nil
}
