// Code generated by SDK builder generator (v0.1.0); DO NOT EDIT.

package sdk

import (
	"testing"
)

var passwordPoliciesTestIdSchemaObjectIdentifier = randomSchemaObjectIdentifier()

const (
	case_PasswordPolicies_validation_Create_name_ValidIdentifier                  testCaseName = "validation_Create_name_ValidIdentifier"
	case_PasswordPolicies_validation_Create_opts_ConflictingFields                testCaseName = "validation_Create_opts_ConflictingFields"
	case_PasswordPolicies_sql_Create_basic                                        testCaseName = "sql_Create_basic"
	case_PasswordPolicies_sql_Create_all                                          testCaseName = "sql_Create_all"
	case_PasswordPolicies_validation_Alter_name_ValidIdentifier                   testCaseName = "validation_Alter_name_ValidIdentifier"
	case_PasswordPolicies_validation_Alter_opts_ExactlyOneValueSet_NoneSet        testCaseName = "validation_Alter_opts_ExactlyOneValueSet_NoneSet"
	case_PasswordPolicies_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet testCaseName = "validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet"
	case_PasswordPolicies_validation_Alter_opts_Set_AtLeastOneValueSet            testCaseName = "validation_Alter_opts_Set_AtLeastOneValueSet"
	case_PasswordPolicies_validation_Alter_opts_Unset_AtLeastOneValueSet          testCaseName = "validation_Alter_opts_Unset_AtLeastOneValueSet"
	case_PasswordPolicies_sql_Alter_Set                                           testCaseName = "sql_Alter_Set"
	case_PasswordPolicies_sql_Alter_Unset                                         testCaseName = "sql_Alter_Unset"
	case_PasswordPolicies_sql_Alter_RenameTo                                      testCaseName = "sql_Alter_RenameTo"
	case_PasswordPolicies_validation_Drop_name_ValidIdentifier                    testCaseName = "validation_Drop_name_ValidIdentifier"
	case_PasswordPolicies_sql_Drop_basic                                          testCaseName = "sql_Drop_basic"
	case_PasswordPolicies_sql_Drop_all                                            testCaseName = "sql_Drop_all"
	case_PasswordPolicies_sql_Show_basic                                          testCaseName = "sql_Show_basic"
	case_PasswordPolicies_sql_Show_all                                            testCaseName = "sql_Show_all"
	case_PasswordPolicies_sql_Show_Like                                           testCaseName = "sql_Show_Like"
	case_PasswordPolicies_sql_Show_In                                             testCaseName = "sql_Show_In"
	case_PasswordPolicies_sql_Show_On                                             testCaseName = "sql_Show_On"
	case_PasswordPolicies_sql_Show_StartsWith                                     testCaseName = "sql_Show_StartsWith"
	case_PasswordPolicies_sql_Show_Limit                                          testCaseName = "sql_Show_Limit"
	case_PasswordPolicies_validation_Describe_name_ValidIdentifier                testCaseName = "validation_Describe_name_ValidIdentifier"
	case_PasswordPolicies_sql_Describe_basic                                      testCaseName = "sql_Describe_basic"
)

type PasswordPoliciesTestsContext struct {
	Create   *sdkTestCtx[*CreatePasswordPolicyOptions]
	Alter    *sdkTestCtx[*AlterPasswordPolicyOptions]
	Drop     *sdkTestCtx[*DropPasswordPolicyOptions]
	Show     *sdkTestCtx[*ShowPasswordPolicyOptions]
	Describe *sdkTestCtx[*DescribePasswordPolicyOptions]
}

var passwordPoliciesTests = PasswordPoliciesTestsContext{
	Create: newSdkTestCtx[*CreatePasswordPolicyOptions](
		"PasswordPolicies", "Create",
	).
		withDefaultOpts(func() *CreatePasswordPolicyOptions {
			return &CreatePasswordPolicyOptions{
				name: passwordPoliciesTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*CreatePasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Create_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *CreatePasswordPolicyOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*CreatePasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Create_opts_ConflictingFields,
				ExpectedErr: errOneOf("CreatePasswordPolicyOptions", "OrReplace", "IfNotExists"),
				DefaultModify: func(opts *CreatePasswordPolicyOptions) {
					opts.OrReplace = new(true)
					opts.IfNotExists = new(true)
				},
			},
		).
		withSqlCases(
			sqlCase[*CreatePasswordPolicyOptions]{
				Name:           case_PasswordPolicies_sql_Create_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*CreatePasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Create_all,
			},
		),
	Alter: newSdkTestCtx[*AlterPasswordPolicyOptions](
		"PasswordPolicies", "Alter",
	).
		withDefaultOpts(func() *AlterPasswordPolicyOptions {
			return &AlterPasswordPolicyOptions{
				name: passwordPoliciesTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*AlterPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Alter_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *AlterPasswordPolicyOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
			validationCase[*AlterPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Alter_opts_ExactlyOneValueSet_NoneSet,
				ExpectedErr: errExactlyOneOf("AlterPasswordPolicyOptions", "Set", "Unset", "RenameTo"),
				DefaultModify: func(opts *AlterPasswordPolicyOptions) {
					opts.Set = nil
					opts.Unset = nil
					opts.RenameTo = nil
				},
			},
			validationCase[*AlterPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Alter_opts_ExactlyOneValueSet_MoreThanOneSet,
				ExpectedErr: errExactlyOneOf("AlterPasswordPolicyOptions", "Set", "Unset", "RenameTo"),
				DefaultModify: func(opts *AlterPasswordPolicyOptions) {
					opts.Set = &PasswordPolicySet{}
					opts.Unset = &PasswordPolicyUnset{}
				},
			},
			validationCase[*AlterPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Alter_opts_Set_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterPasswordPolicyOptions.Set", "PasswordMinLength", "PasswordMaxLength", "PasswordMinUpperCaseChars", "PasswordMinLowerCaseChars", "PasswordMinNumericChars", "PasswordMinSpecialChars", "PasswordMinAgeDays", "PasswordMaxAgeDays", "PasswordMaxRetries", "PasswordLockoutTimeMins", "PasswordHistory", "Comment"),
				DefaultModify: func(opts *AlterPasswordPolicyOptions) {
					opts.Set = &PasswordPolicySet{}
					opts.Set.PasswordMinLength = nil
					opts.Set.PasswordMaxLength = nil
					opts.Set.PasswordMinUpperCaseChars = nil
					opts.Set.PasswordMinLowerCaseChars = nil
					opts.Set.PasswordMinNumericChars = nil
					opts.Set.PasswordMinSpecialChars = nil
					opts.Set.PasswordMinAgeDays = nil
					opts.Set.PasswordMaxAgeDays = nil
					opts.Set.PasswordMaxRetries = nil
					opts.Set.PasswordLockoutTimeMins = nil
					opts.Set.PasswordHistory = nil
					opts.Set.Comment = nil
				},
			},
			validationCase[*AlterPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Alter_opts_Unset_AtLeastOneValueSet,
				ExpectedErr: errAtLeastOneOf("AlterPasswordPolicyOptions.Unset", "PasswordMinLength", "PasswordMaxLength", "PasswordMinUpperCaseChars", "PasswordMinLowerCaseChars", "PasswordMinNumericChars", "PasswordMinSpecialChars", "PasswordMinAgeDays", "PasswordMaxAgeDays", "PasswordMaxRetries", "PasswordLockoutTimeMins", "PasswordHistory", "Comment"),
				DefaultModify: func(opts *AlterPasswordPolicyOptions) {
					opts.Unset = &PasswordPolicyUnset{}
					opts.Unset.PasswordMinLength = nil
					opts.Unset.PasswordMaxLength = nil
					opts.Unset.PasswordMinUpperCaseChars = nil
					opts.Unset.PasswordMinLowerCaseChars = nil
					opts.Unset.PasswordMinNumericChars = nil
					opts.Unset.PasswordMinSpecialChars = nil
					opts.Unset.PasswordMinAgeDays = nil
					opts.Unset.PasswordMaxAgeDays = nil
					opts.Unset.PasswordMaxRetries = nil
					opts.Unset.PasswordLockoutTimeMins = nil
					opts.Unset.PasswordHistory = nil
					opts.Unset.Comment = nil
				},
			},
		).
		withSqlCases(
			sqlCase[*AlterPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Alter_Set,
			},
			sqlCase[*AlterPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Alter_Unset,
			},
			sqlCase[*AlterPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Alter_RenameTo,
			},
		),
	Drop: newSdkTestCtx[*DropPasswordPolicyOptions](
		"PasswordPolicies", "Drop",
	).
		withDefaultOpts(func() *DropPasswordPolicyOptions {
			return &DropPasswordPolicyOptions{
				name: passwordPoliciesTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DropPasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Drop_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DropPasswordPolicyOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DropPasswordPolicyOptions]{
				Name:           case_PasswordPolicies_sql_Drop_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*DropPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Drop_all,
			},
		),
	Show: newSdkTestCtx[*ShowPasswordPolicyOptions](
		"PasswordPolicies", "Show",
	).
		withDefaultOpts(func() *ShowPasswordPolicyOptions {
			return &ShowPasswordPolicyOptions{}
		}).
		withValidationCases().
		withSqlCases(
			sqlCase[*ShowPasswordPolicyOptions]{
				Name:           case_PasswordPolicies_sql_Show_basic,
				NoModifyNeeded: true,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_all,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_Like,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_In,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_On,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_StartsWith,
			},
			sqlCase[*ShowPasswordPolicyOptions]{
				Name: case_PasswordPolicies_sql_Show_Limit,
			},
		),
	Describe: newSdkTestCtx[*DescribePasswordPolicyOptions](
		"PasswordPolicies", "Describe",
	).
		withDefaultOpts(func() *DescribePasswordPolicyOptions {
			return &DescribePasswordPolicyOptions{
				name: passwordPoliciesTestIdSchemaObjectIdentifier,
			}
		}).
		withValidationCases(
			validationCase[*DescribePasswordPolicyOptions]{
				Name:        case_PasswordPolicies_validation_Describe_name_ValidIdentifier,
				ExpectedErr: ErrInvalidObjectIdentifier,
				DefaultModify: func(opts *DescribePasswordPolicyOptions) {
					opts.name = emptySchemaObjectIdentifier
				},
			},
		).
		withSqlCases(
			sqlCase[*DescribePasswordPolicyOptions]{
				Name:           case_PasswordPolicies_sql_Describe_basic,
				NoModifyNeeded: true,
			},
		),
}

func TestPasswordPolicies_Create(t *testing.T) {
	passwordPoliciesTests.Create.RunValidationCases(t)
	passwordPoliciesTests.Create.RunSqlCases(t)
}

func TestPasswordPolicies_Alter(t *testing.T) {
	passwordPoliciesTests.Alter.RunValidationCases(t)
	passwordPoliciesTests.Alter.RunSqlCases(t)
}

func TestPasswordPolicies_Drop(t *testing.T) {
	passwordPoliciesTests.Drop.RunValidationCases(t)
	passwordPoliciesTests.Drop.RunSqlCases(t)
}

func TestPasswordPolicies_Show(t *testing.T) {
	passwordPoliciesTests.Show.RunValidationCases(t)
	passwordPoliciesTests.Show.RunSqlCases(t)
}

func TestPasswordPolicies_Describe(t *testing.T) {
	passwordPoliciesTests.Describe.RunValidationCases(t)
	passwordPoliciesTests.Describe.RunSqlCases(t)
}
