// Code generated by blueprint generator; DO NOT EDIT.

package sdk

import (
	"context"
)

type PipesGen interface {
	// Create creates a pipe.
	Create(ctx context.Context, opts *PipeCreateOptionsGen) error
}

// PipeCreateOptionsGen contains options for creating a new pipe in the system for defining the COPY INTO <table> statement used by Snowpipe to load data from an ingestion queue into tables.
//
// Based on https://docs.snowflake.com/en/sql-reference/sql/create-pipe
type PipeCreateOptionsGen struct {
	create      bool                   `ddl:"static" sql:"CREATE"` //lint:ignore U1000 This is used in the ddl tag
	OrReplace   *bool                  `ddl:"keyword" sql:"OR REPLACE"`
	pipe        bool                   `ddl:"static" sql:"PIPE"` //lint:ignore U1000 This is used in the ddl tag
	IfNotExists *bool                  `ddl:"keyword" sql:"IF NOT EXISTS"`
	name        SchemaObjectIdentifier `ddl:"identifier"`

	Auto_ingest       *bool   `ddl:"parameter,no_quotes" sql:"AUTO_INGEST"`
	Error_integration *string `ddl:"parameter,no_quotes" sql:"ERROR_INTEGRATION"`
	Aws_sns_topic     *string `ddl:"parameter,single_quotes" sql:"AWS_SNS_TOPIC"`
	Integration       *string `ddl:"parameter,single_quotes" sql:"INTEGRATION"`
	Comment           *string `ddl:"parameter,single_quotes" sql:"COMMENT"`

	As As `ddl:"list" sql:"AS"`
}

type As struct {
	Copy_statement string `ddl:"keyword,no_quotes"`
}
