// Code generated by assertions generator; DO NOT EDIT.

package resourceassert

import (
	"testing"

	"github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/acceptance/bettertestspoc/assert"
)

type StreamOnTableResourceAssert struct {
	*assert.ResourceAssert
}

func StreamOnTableResource(t *testing.T, name string) *StreamOnTableResourceAssert {
	t.Helper()

	return &StreamOnTableResourceAssert{
		ResourceAssert: assert.NewResourceAssert(name, "resource"),
	}
}

func ImportedStreamOnTableResource(t *testing.T, id string) *StreamOnTableResourceAssert {
	t.Helper()

	return &StreamOnTableResourceAssert{
		ResourceAssert: assert.NewImportedResourceAssert(id, "imported resource"),
	}
}

///////////////////////////////////
// Attribute value string checks //
///////////////////////////////////

func (s *StreamOnTableResourceAssert) HasAppendOnlyString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("append_only", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasAtString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("at", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasBeforeString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("before", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasCommentString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("comment", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasCopyGrantsString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("copy_grants", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasDatabaseString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("database", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasFullyQualifiedNameString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("fully_qualified_name", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasNameString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("name", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasSchemaString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("schema", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasShowInitialRowsString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("show_initial_rows", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasStaleString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("stale", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasStreamTypeString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("stream_type", expected))
	return s
}

func (s *StreamOnTableResourceAssert) HasTableString(expected string) *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("table", expected))
	return s
}

///////////////////////////////
// Attribute no value checks //
///////////////////////////////

func (s *StreamOnTableResourceAssert) HasNoAppendOnly() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("append_only"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoAt() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("at.#", "0"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoBefore() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("before.#", "0"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoComment() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("comment"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoCopyGrants() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("copy_grants"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoDatabase() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("database"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoFullyQualifiedName() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("fully_qualified_name"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoName() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("name"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoSchema() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("schema"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoShowInitialRows() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("show_initial_rows"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoStale() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("stale"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoStreamType() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("stream_type"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNoTable() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueNotSet("table"))
	return s
}

////////////////////////////
// Attribute empty checks //
////////////////////////////

func (s *StreamOnTableResourceAssert) HasAppendOnlyEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("append_only", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasCommentEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("comment", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasDatabaseEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("database", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasFullyQualifiedNameEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("fully_qualified_name", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasNameEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("name", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasSchemaEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("schema", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasShowInitialRowsEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("show_initial_rows", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasStreamTypeEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("stream_type", ""))
	return s
}
func (s *StreamOnTableResourceAssert) HasTableEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValueSet("table", ""))
	return s
}

///////////////////////////////
// Attribute presence checks //
///////////////////////////////

func (s *StreamOnTableResourceAssert) HasAppendOnlyNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("append_only"))
	return s
}

func (s *StreamOnTableResourceAssert) HasAtNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("at"))
	return s
}

func (s *StreamOnTableResourceAssert) HasBeforeNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("before"))
	return s
}

func (s *StreamOnTableResourceAssert) HasCommentNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("comment"))
	return s
}

func (s *StreamOnTableResourceAssert) HasCopyGrantsNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("copy_grants"))
	return s
}

func (s *StreamOnTableResourceAssert) HasDatabaseNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("database"))
	return s
}

func (s *StreamOnTableResourceAssert) HasFullyQualifiedNameNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("fully_qualified_name"))
	return s
}

func (s *StreamOnTableResourceAssert) HasNameNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("name"))
	return s
}

func (s *StreamOnTableResourceAssert) HasSchemaNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("schema"))
	return s
}

func (s *StreamOnTableResourceAssert) HasShowInitialRowsNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("show_initial_rows"))
	return s
}

func (s *StreamOnTableResourceAssert) HasStaleNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("stale"))
	return s
}

func (s *StreamOnTableResourceAssert) HasStreamTypeNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("stream_type"))
	return s
}

func (s *StreamOnTableResourceAssert) HasTableNotEmpty() *StreamOnTableResourceAssert {
	s.AddAssertion(assert.ValuePresent("table"))
	return s
}
