package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var (
	blueprintPath     = flag.String("blueprint", "", ".json file containing blueprint for generation; must be set")
	lintIgnoreComment = "//lint:ignore U1000 This is used in the ddl tag"
)

func main() {
	fmt.Printf("Running generator on %s with args %#v\n", os.Getenv("GOFILE"), os.Args[1:])

	blueprint := loadBlueprint()
	fmt.Printf("Loaded blueprint %#v.\n", blueprint)

	gen := setUpGenerator(blueprint)
	fmt.Printf("Generator set up for package \"%s\" with output name \"%s\".\n", gen.outputPackage, gen.outputName)

	gen.addFilePreamble()
	gen.generateCreate()

	src, errSrcFormat := format.Source(gen.Buffer.Bytes())
	if errSrcFormat != nil {
		log.Panicln(errSrcFormat)
	}
	if err := os.WriteFile(gen.outputName, src, 0644); err != nil {
		log.Panicln(err)
	}
}

func loadBlueprint() *Blueprint {
	flag.Parse()

	if len(*blueprintPath) == 0 {
		flag.Usage()
		log.Panicln("Blueprint .json file was not specified.")
	}

	blueprintFile, errOpenFile := os.Open(*blueprintPath)
	if errOpenFile != nil {
		log.Panicln(errOpenFile)
	}
	defer blueprintFile.Close()
	fmt.Printf("Opened blueprint file %s\n", blueprintFile.Name())

	byteValue, errReadBytes := io.ReadAll(blueprintFile)
	if errReadBytes != nil {
		log.Panicln(errReadBytes)
	}

	var blueprint Blueprint
	if err := json.Unmarshal(byteValue, &blueprint); err != nil {
		log.Panicln(err)
	}
	return &blueprint
}

type Blueprint struct {
	Object Object `json:"object"`
	Create Create `json:"create"`
}

type Object struct {
	Name string `json:"name"`
}

type Create struct {
	Docs      string          `json:"docs"`
	Modifiers CreateModifiers `json:"modifiers"`
	Fields    []CreateField   `json:"fields"`
}

type CreateModifiers struct {
	OrReplace   bool `json:"orReplace"`
	IfNotExists bool `json:"ifNotExists"`
}

type CreateField struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Quotations string `json:"quotations"`
}

func setUpGenerator(blueprint *Blueprint) *Generator {
	wd, errWd := os.Getwd()
	if errWd != nil {
		log.Panicln(errWd)
	}

	file := os.Getenv("GOFILE")
	fileWithoutSuffix, _ := strings.CutSuffix(file, ".go")
	baseName := fmt.Sprintf("%s_generated.go", fileWithoutSuffix)
	outputName := filepath.Join(wd, baseName)

	return &Generator{
		Buffer:        bytes.Buffer{},
		blueprint:     blueprint,
		outputPackage: os.Getenv("GOPACKAGE"),
		outputName:    outputName,
	}
}

type Generator struct {
	Buffer        bytes.Buffer
	blueprint     *Blueprint
	outputPackage string
	outputName    string
}

func (gen *Generator) printf(format string, args ...any) {
	_, err := fmt.Fprintf(&gen.Buffer, format, args...)
	if err != nil {
		log.Panicln(err)
	}
}

func (gen *Generator) addFilePreamble() {
	gen.printf("// Code generated by blueprint generator; DO NOT EDIT.\n")
	gen.printf("\n")
	gen.printf("package %s\n", gen.outputPackage)
	gen.printf("\n")
}

// TODO: implement using go text/template or at least clean it
func (gen *Generator) generateCreate() {
	gen.printf("// Based on %s\n", gen.blueprint.Create.Docs)
	gen.printf("type %sCreateOptionsGen struct {\n", strings.Title(gen.blueprint.Object.Name))

	// create section is almost the same everytime
	gen.printf("create bool `ddl:\"static\" sql:\"CREATE\"` %s\n", lintIgnoreComment)

	gen.printf("}\n")
	gen.printf("\n")
}
