package snowflakeenvs

const (
	Account                   = "SNOWFLAKE_ACCOUNT"
	User                      = "SNOWFLAKE_USER"
	Username                  = "SNOWFLAKE_USERNAME"
	Password                  = "SNOWFLAKE_PASSWORD"
	Warehouse                 = "SNOWFLAKE_WAREHOUSE"
	Role                      = "SNOWFLAKE_ROLE"
	ValidateDefaultParameters = "SNOWFLAKE_VALIDATE_DEFAULT_PARAMETERS"
	ClientIp                  = "SNOWFLAKE_CLIENT_IP"
	Protocol                  = "SNOWFLAKE_PROTOCOL"
	Host                      = "SNOWFLAKE_HOST"
	Port                      = "SNOWFLAKE_PORT"
	Authenticator             = "SNOWFLAKE_AUTHENTICATOR"
	Passcode                  = "SNOWFLAKE_PASSCODE"
	PasscodeInPassword        = "SNOWFLAKE_PASSCODE_IN_PASSWORD"
	OktaUrl                   = "SNOWFLAKE_OKTA_URL"
	LoginTimeout              = "SNOWFLAKE_LOGIN_TIMEOUT"
	RequestTimeout            = "SNOWFLAKE_REQUEST_TIMEOUT"
	JwtExpireTimeout          = "SNOWFLAKE_JWT_EXPIRE_TIMEOUT"
	ClientTimeout             = "SNOWFLAKE_CLIENT_TIMEOUT"
	JwtClientTimeout          = "SNOWFLAKE_JWT_CLIENT_TIMEOUT"
	ExternalBrowserTimeout    = "SNOWFLAKE_EXTERNAL_BROWSER_TIMEOUT"
	InsecureMode              = "SNOWFLAKE_INSECURE_MODE"
	OcspFailOpen              = "SNOWFLAKE_OCSP_FAIL_OPEN"

	Token                      = "SNOWFLAKE_TOKEN"
	TokenAccessorTokenEndpoint = "SNOWFLAKE_TOKEN_ACCESSOR_TOKEN_ENDPOINT"
	TokenAccessorRefreshToken  = "SNOWFLAKE_TOKEN_ACCESSOR_REFRESH_TOKEN"
	TokenAccessorClientId      = "SNOWFLAKE_TOKEN_ACCESSOR_CLIENT_ID"
	TokenAccessorClientSecret  = "SNOWFLAKE_TOKEN_ACCESSOR_CLIENT_SECRET"
	TokenAccessorRedirectUri   = "SNOWFLAKE_TOKEN_ACCESSOR_REDIRECT_URI"

	KeepSessionAlive               = "SNOWFLAKE_KEEP_SESSION_ALIVE"
	PrivateKey                     = "SNOWFLAKE_PRIVATE_KEY"
	PrivateKeyPassphrase           = "SNOWFLAKE_PRIVATE_KEY_PASSPHRASE"
	DisableTelemetry               = "DISABLE_TELEMETRY"
	ClientRequestMfaToken          = "SNOWFLAKE_CLIENT_REQUEST_MFA_TOKEN"
	ClientStoreTemporaryCredential = "SNOWFLAKE_CLIENT_STORE_TEMPORARY_CREDENTIAL"
	DisableQueryContextCache       = "SNOWFLAKE_DISABLE_QUERY_CONTEXT_CACHE"
	IncludeRetryReason             = "SNOWFLAKE_INCLUDE_RETRY_REASON"
	Profile                        = "SNOWFLAKE_PROFILE"

	ConfigPath = "SNOWFLAKE_CONFIG_PATH"

	NoInstrumentedSql   = "SF_TF_NO_INSTRUMENTED_SQL"
	GosnowflakeLogLevel = "SF_TF_GOSNOWFLAKE_LOG_LEVEL"
)
