package resources

type resource string

const (
	Account                                                resource = "snowflake_account"
	AccountAuthenticationPolicyAttachment                  resource = "snowflake_account_authentication_policy_attachment"
	AccountParameter                                       resource = "snowflake_account_parameter"
	AccountPasswordPolicyAttachment                        resource = "snowflake_account_password_policy_attachment"
	AccountRole                                            resource = "snowflake_account_role"
	AccountSessionPolicyAttachment                         resource = "snowflake_account_session_policy_attachment"
	Alert                                                  resource = "snowflake_alert"
	ApiAuthenticationIntegrationWithAuthorizationCodeGrant resource = "snowflake_api_authentication_integration_with_authorization_code_grant"
	ApiAuthenticationIntegrationWithClientCredentials      resource = "snowflake_api_authentication_integration_with_client_credentials"
	ApiAuthenticationIntegrationWithJwtBearer              resource = "snowflake_api_authentication_integration_with_jwt_bearer"
	ApiIntegration                                         resource = "snowflake_api_integration"
	ApiIntegrationAmazonApiGateway                         resource = "snowflake_api_integration_amazon_api_gateway"
	ApiIntegrationAzureApiManagement                       resource = "snowflake_api_integration_azure_api_management"
	ApiIntegrationExternalMcpDynamicClient                 resource = "snowflake_api_integration_external_mcp_dynamic_client"
	ApiIntegrationExternalMcpOAuth2                        resource = "snowflake_api_integration_external_mcp_oauth2"
	ApiIntegrationGitRepositoryGithubApp                   resource = "snowflake_api_integration_git_repository_github_app"
	ApiIntegrationGitRepositoryOauth2                      resource = "snowflake_api_integration_git_repository_oauth2"
	ApiIntegrationGitRepositoryPrivateLink                 resource = "snowflake_api_integration_git_repository_private_link"
	ApiIntegrationGitRepositoryToken                       resource = "snowflake_api_integration_git_repository_token"
	ApiIntegrationGoogleCloudApiGateway                    resource = "snowflake_api_integration_google_cloud_api_gateway"
	AuthenticationPolicy                                   resource = "snowflake_authentication_policy"
	CatalogIntegrationAwsGlue                              resource = "snowflake_catalog_integration_aws_glue"
	CatalogIntegrationObjectStorage                        resource = "snowflake_catalog_integration_object_storage"
	CatalogIntegrationOpenCatalog                          resource = "snowflake_catalog_integration_open_catalog"
	CatalogIntegrationIcebergRest                          resource = "snowflake_catalog_integration_iceberg_rest"
	ComputePool                                            resource = "snowflake_compute_pool"
	CortexAgent                                            resource = "snowflake_cortex_agent"
	CortexSearchService                                    resource = "snowflake_cortex_search_service"
	CurrentAccount                                         resource = "snowflake_current_account"
	CurrentOrganizationAccount                             resource = "snowflake_current_organization_account"
	Database                                               resource = "snowflake_database"
	DatabaseRole                                           resource = "snowflake_database_role"
	DynamicTable                                           resource = "snowflake_dynamic_table"
	EmailNotificationIntegration                           resource = "snowflake_email_notification_integration"
	Execute                                                resource = "snowflake_execute"
	ExternalAccessIntegration                              resource = "snowflake_external_access_integration"
	ExternalAzureStage                                     resource = "snowflake_stage_external_azure"
	ExternalFunction                                       resource = "snowflake_external_function"
	ExternalGcsStage                                       resource = "snowflake_stage_external_gcs"
	ExternalS3Stage                                        resource = "snowflake_stage_external_s3"
	ExternalS3CompatibleStage                              resource = "snowflake_stage_external_s3_compatible"
	ExternalTable                                          resource = "snowflake_external_table"
	ExternalOauthSecurityIntegration                       resource = "snowflake_external_oauth_integration"
	ExternalVolume                                         resource = "snowflake_external_volume"
	FailoverGroup                                          resource = "snowflake_failover_group"
	FileFormat                                             resource = "snowflake_file_format"
	FileFormatAvro                                         resource = "snowflake_file_format_avro"
	FileFormatCsv                                          resource = "snowflake_file_format_csv"
	FileFormatJson                                         resource = "snowflake_file_format_json"
	FileFormatOrc                                          resource = "snowflake_file_format_orc"
	FileFormatParquet                                      resource = "snowflake_file_format_parquet"
	FileFormatXml                                          resource = "snowflake_file_format_xml"
	FunctionJava                                           resource = "snowflake_function_java"
	FunctionJavascript                                     resource = "snowflake_function_javascript"
	FunctionPython                                         resource = "snowflake_function_python"
	FunctionScala                                          resource = "snowflake_function_scala"
	FunctionSql                                            resource = "snowflake_function_sql"
	GitRepository                                          resource = "snowflake_git_repository"
	GrantAccountRole                                       resource = "snowflake_grant_account_role"
	GrantApplicationRole                                   resource = "snowflake_grant_application_role"
	GrantDatabaseRole                                      resource = "snowflake_grant_database_role"
	GrantOwnership                                         resource = "snowflake_grant_ownership"
	GrantPrivilegesToAccountRole                           resource = "snowflake_grant_privileges_to_account_role"
	GrantPrivilegesToDatabaseRole                          resource = "snowflake_grant_privileges_to_database_role"
	GrantPrivilegesToShare                                 resource = "snowflake_grant_privileges_to_share"
	HybridTable                                            resource = "snowflake_hybrid_table"
	IcebergTable                                           resource = "snowflake_iceberg_table"
	IcebergTableFromAwsGlue                                resource = "snowflake_iceberg_table_from_aws_glue"
	IcebergTableFromDeltaFiles                             resource = "snowflake_iceberg_table_from_delta_files"
	IcebergTableFromFiles                                  resource = "snowflake_iceberg_table_from_files"
	IcebergTableFromRest                                   resource = "snowflake_iceberg_table_from_rest"
	ImageRepository                                        resource = "snowflake_image_repository"
	InternalStage                                          resource = "snowflake_stage_internal"
	JobService                                             resource = "snowflake_job_service"
	LegacyServiceUser                                      resource = "snowflake_legacy_service_user"
	Listing                                                resource = "snowflake_listing"
	ManagedAccount                                         resource = "snowflake_managed_account"
	MaskingPolicy                                          resource = "snowflake_masking_policy"
	MaterializedView                                       resource = "snowflake_materialized_view"
	McpServer                                              resource = "snowflake_mcp_server"
	NetworkPolicy                                          resource = "snowflake_network_policy"
	NetworkPolicyAttachment                                resource = "snowflake_network_policy_attachment"
	NetworkRule                                            resource = "snowflake_network_rule"
	Notebook                                               resource = "snowflake_notebook"
	NotificationIntegration                                resource = "snowflake_notification_integration"
	OauthIntegration                                       resource = "snowflake_oauth_integration"
	OauthIntegrationForCustomClients                       resource = "snowflake_oauth_integration_for_custom_clients"
	OauthIntegrationForPartnerApplications                 resource = "snowflake_oauth_integration_for_partner_applications"
	ObjectParameter                                        resource = "snowflake_object_parameter"
	OpenflowDeploymentByoc                                 resource = "snowflake_openflow_deployment_byoc"
	OpenflowDeploymentSnowflakeManaged                     resource = "snowflake_openflow_deployment_snowflake_managed"
	PasswordPolicy                                         resource = "snowflake_password_policy"
	Pipe                                                   resource = "snowflake_pipe"
	PostgresFork                                           resource = "snowflake_postgres_fork"
	PostgresInstance                                       resource = "snowflake_postgres_instance"
	PrimaryConnection                                      resource = "snowflake_primary_connection"
	ProcedureJava                                          resource = "snowflake_procedure_java"
	ProcedureJavascript                                    resource = "snowflake_procedure_javascript"
	ProcedurePython                                        resource = "snowflake_procedure_python"
	ProcedureScala                                         resource = "snowflake_procedure_scala"
	ProcedureSql                                           resource = "snowflake_procedure_sql"
	ResourceMonitor                                        resource = "snowflake_resource_monitor"
	RowAccessPolicy                                        resource = "snowflake_row_access_policy"
	SamlSecurityIntegration                                resource = "snowflake_saml_integration"
	Saml2SecurityIntegration                               resource = "snowflake_saml2_integration"
	Schema                                                 resource = "snowflake_schema"
	ScimSecurityIntegration                                resource = "snowflake_scim_integration"
	SecondaryConnection                                    resource = "snowflake_secondary_connection"
	SecondaryDatabase                                      resource = "snowflake_secondary_database"
	SecretWithAuthorizationCodeGrant                       resource = "snowflake_secret_with_authorization_code_grant"
	SecretWithBasicAuthentication                          resource = "snowflake_secret_with_basic_authentication"
	SecretWithClientCredentials                            resource = "snowflake_secret_with_client_credentials"
	SecretWithGenericString                                resource = "snowflake_secret_with_generic_string"
	SemanticView                                           resource = "snowflake_semantic_view"
	SessionParameter                                       resource = "snowflake_session_parameter"
	SessionPolicy                                          resource = "snowflake_session_policy"
	Sequence                                               resource = "snowflake_sequence"
	Service                                                resource = "snowflake_service"
	ServiceUser                                            resource = "snowflake_service_user"
	Share                                                  resource = "snowflake_share"
	SharedDatabase                                         resource = "snowflake_shared_database"
	Stage                                                  resource = "snowflake_stage"
	StorageIntegration                                     resource = "snowflake_storage_integration"
	StorageIntegrationAws                                  resource = "snowflake_storage_integration_aws"
	StorageIntegrationAzure                                resource = "snowflake_storage_integration_azure"
	StorageIntegrationGcs                                  resource = "snowflake_storage_integration_gcs"
	StorageLifecyclePolicy                                 resource = "snowflake_storage_lifecycle_policy"
	StreamOnDirectoryTable                                 resource = "snowflake_stream_on_directory_table"
	StreamOnExternalTable                                  resource = "snowflake_stream_on_external_table"
	StreamOnTable                                          resource = "snowflake_stream_on_table"
	StreamOnView                                           resource = "snowflake_stream_on_view"
	Streamlit                                              resource = "snowflake_streamlit"
	Table                                                  resource = "snowflake_table"
	TableColumnMaskingPolicyApplication                    resource = "snowflake_table_column_masking_policy_application"
	TableConstraint                                        resource = "snowflake_table_constraint"
	Tag                                                    resource = "snowflake_tag"
	TagAssociation                                         resource = "snowflake_tag_association"
	TagMaskingPolicyAssociation                            resource = "snowflake_tag_masking_policy_association"
	Task                                                   resource = "snowflake_task"
	User                                                   resource = "snowflake_user"
	UserAuthenticationPolicyAttachment                     resource = "snowflake_user_authentication_policy_attachment"
	UserPasswordPolicyAttachment                           resource = "snowflake_user_password_policy_attachment"
	UserPublicKeys                                         resource = "snowflake_user_public_keys"
	UserProgrammaticAccessToken                            resource = "snowflake_user_programmatic_access_token"
	UserSessionPolicyAttachment                            resource = "snowflake_user_session_policy_attachment"
	TableStorageLifecyclePolicyAttachment                  resource = "snowflake_table_storage_lifecycle_policy_attachment"
	View                                                   resource = "snowflake_view"
	Warehouse                                              resource = "snowflake_warehouse"
	WarehouseAdaptive                                      resource = "snowflake_warehouse_adaptive"
	WarehouseInteractive                                   resource = "snowflake_warehouse_interactive"
)

type Resource interface {
	xxxProtected()
	String() string
}

func (r resource) xxxProtected() {}

func (r resource) String() string {
	return string(r)
}
