package assert

func (w *UserParametersAssert) HasAllDefaultsExplicit() *UserParametersAssert {
	return w.
		HasDefaultEnableUnredactedQuerySyntaxErrorValueExplicit().
		HasDefaultNetworkPolicyValueExplicit().
		HasDefaultPreventUnloadToInternalStagesValueExplicit().
		HasDefaultAbortDetachedQueryValueExplicit().
		HasDefaultAutocommitValueExplicit().
		HasDefaultBinaryInputFormatValueExplicit().
		HasDefaultBinaryOutputFormatValueExplicit().
		HasDefaultClientMemoryLimitValueExplicit().
		HasDefaultClientMetadataRequestUseConnectionCtxValueExplicit().
		HasDefaultClientPrefetchThreadsValueExplicit().
		HasDefaultClientResultChunkSizeValueExplicit().
		HasDefaultClientResultColumnCaseInsensitiveValueExplicit().
		HasDefaultClientSessionKeepAliveValueExplicit().
		HasDefaultClientSessionKeepAliveHeartbeatFrequencyValueExplicit().
		HasDefaultClientTimestampTypeMappingValueExplicit().
		HasDefaultDateInputFormatValueExplicit().
		HasDefaultDateOutputFormatValueExplicit().
		HasDefaultEnableUnloadPhysicalTypeOptimizationValueExplicit().
		HasDefaultErrorOnNondeterministicMergeValueExplicit().
		HasDefaultErrorOnNondeterministicUpdateValueExplicit().
		HasDefaultGeographyOutputFormatValueExplicit().
		HasDefaultGeometryOutputFormatValueExplicit().
		HasDefaultJdbcTreatDecimalAsIntValueExplicit().
		HasDefaultJdbcTreatTimestampNtzAsUtcValueExplicit().
		HasDefaultJdbcUseSessionTimezoneValueExplicit().
		HasDefaultJsonIndentValueExplicit().
		HasDefaultLockTimeoutValueExplicit().
		HasDefaultLogLevelValueExplicit().
		HasDefaultMultiStatementCountValueExplicit().
		HasDefaultNoorderSequenceAsDefaultValueExplicit().
		HasDefaultOdbcTreatDecimalAsIntValueExplicit().
		HasDefaultQueryTagValueExplicit().
		HasDefaultQuotedIdentifiersIgnoreCaseValueExplicit().
		HasDefaultRowsPerResultsetValueExplicit().
		HasDefaultS3StageVpceDnsNameValueExplicit().
		HasDefaultSearchPathValueExplicit().
		HasDefaultSimulatedDataSharingConsumerValueExplicit().
		HasDefaultStatementQueuedTimeoutInSecondsValueExplicit().
		HasDefaultStatementTimeoutInSecondsValueExplicit().
		HasDefaultStrictJsonOutputValueExplicit().
		HasDefaultTimestampDayIsAlways24hValueExplicit().
		HasDefaultTimestampInputFormatValueExplicit().
		HasDefaultTimestampLtzOutputFormatValueExplicit().
		HasDefaultTimestampNtzOutputFormatValueExplicit().
		HasDefaultTimestampOutputFormatValueExplicit().
		HasDefaultTimestampTypeMappingValueExplicit().
		HasDefaultTimestampTzOutputFormatValueExplicit().
		HasDefaultTimezoneValueExplicit().
		HasDefaultTimeInputFormatValueExplicit().
		HasDefaultTimeOutputFormatValueExplicit().
		HasDefaultTraceLevelValueExplicit().
		HasDefaultTransactionAbortOnErrorValueExplicit().
		HasDefaultTransactionDefaultIsolationLevelValueExplicit().
		HasDefaultTwoDigitCenturyStartValueExplicit().
		HasDefaultUnsupportedDdlActionValueExplicit().
		HasDefaultUseCachedResultValueExplicit().
		HasDefaultWeekOfYearPolicyValueExplicit().
		HasDefaultWeekStartValueExplicit()
}
