on: push

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-docs
          - check-mod
          - lint-ci
          - test-acceptance-ci
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - name: Install dependencies
        run: make setup

      - name: make ${{ matrix.target }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        run: make ${{ matrix.target }}
