# If someone with write access comments "/ok-to-test" on a pull request, emit repository_dispatch event
name: ok-to-test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    environment: ok-to-test
    runs-on: ubuntu-latest
    steps:
      - name: Create token
        id: create-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4
        with:
          token: ${{ steps.create-token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          permission: write
