# If someone with write access comments "/ok-to-test" on a pull request, emit a repository_dispatch event
name: Label

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: chanzuckerberg/github-app-token@v1.1.4
      with:
        app_id: ${{ secrets.OK_TO_TEST_APP_ID }}
        private_key: ${{ secrets.OK_TO_TEST_PRIVATE_KEY }}

    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v1
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        token: ${{ env.TOKEN }} # GitHub App installation access token
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        named-args: true
        commands: ok-to-test
        permission: write

    - name: Output command and arguments
      run: |
        echo ${{ github.event.client_payload.slash_command.sha }}
        echo ${{ github.event.client_payload.pull_request.head.sha }}
