# If someone with write access comments "/ok-to-test" on a pull request, emit repository_dispatch event
name: ok-to-test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: chanzuckerberg/github-app-token@v1.1.4
        with:
          app_id: ${{ secrets.OK_TO_TEST_APP_ID }}
          private_key: ${{ secrets.OK_TO_TEST_PRIVATE_KEY }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
          ACTIONS_STEP_DEBUG: true
        with:
          token: ${{ env.TOKEN }} # GitHub App installation access token
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          issue-type: pull-request
          commands: ok-to-test
          permission: write
