name: Workflow rules

on:
  pull_request:

jobs:
  check_workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for pull_request_target
        run: |
          if grep -r --exclude="workflow-rules.yml" "pull_request_target" .github/workflows/; then
            echo "pull_request_target found in workflow files"
            exit 1
          else
            exit 0
          fi
